### PR TITLE
nsc-events-nextjs-9-544-event-note-optional-visible-only-createdby-admin

### PR DESCRIPTION
**Pull request by Ali-7s**
Satisfies #544 

This PR makes the event notes visible only to the creator of the event or user with the role "admin"

https://github.com/user-attachments/assets/e9504d8d-1d37-4f3e-ba00-0628f2e1eb04

### CODE REVIEW

**Review by keiffer213 — APPROVED** [review]
This worked well for me! I was not able to see the event notes if I was not the creator who made the event

https://github.com/user-attachments/assets/716bb9c1-0d4b-4b8d-a1a4-5181c08b3a90

**Review by intisarosman1 — APPROVED** [review]
When not logged in as the original creator of the event, I am not able to see the event notes, but I can if I am an admin. LGTM
Screenshot 2024-07-16 194551
Screenshot 2024-07-16 195257

**Review by ken-ni — APPROVED** [review]
I tested viewing events on admin, creator and user and it seems to function exactly as you described. Admins can see any event notes, creators are able to view event notes for events they created and users can't see any event notes. Great job!

**Review by heosman — APPROVED** [review]
The changes look good, I can only see the Event Note as the creator of the event or as an admin.

**Pull request merged**
