### PR TITLE
nsc-events-nextjs_9_528_responsive-ui-for-home-page

### LINKED ISSUE #528: Refactor: Responsive UI for Home page
Tasks:

- [x] Adjust so that page elements on these pages are not broken or cropped or off-screen for tablet & mobile screens. Users shouldn't have to side-scroll to view whole page
- [x] Conditionally render the top right “Upcoming Event” to not display on smaller screens using breakpoints. 
- [x] The events should be centered and include event photo.

### PR DESCRIPTION
**Pull request by heosman**
Resolves #528 

This PR 
- Implements responsive UI for the Home page
- Implements responsive UI for My Events and Archived Events pages again (changes were reverted for some reason) 
- Refactored Home page and Event Detail and other pages to use inline styling instead of stylesheets

Home page on desktop/laptop (signed in):
image

Home page on tablet:
image
image

Home page on mobile screen (not signed in):
image
Home page on mobile screen (signed in):
image

### CODE REVIEW

**Comment by Bejarano03** [comment]
Good work thus far. I like what you are doing, and was able to checkout your branch and test out some of the styling done. I like your implementation of flex so that its more responsive.

**Review by ken-ni — APPROVED** [review]
These changes look really good, great job! What prompted you to change from stylesheets to in-line styling instead?
Desktop Events page
all_events_desktop
Home page Desktop (signed out)
signed_out_desktop
Home page Tablet (signed out)
signed_out_tablet
Home page Mobile (signed out)
Signed_out_mobile
My Events Tablet
My_events_tablet
My Events Mobile
My_events_mobile

**Comment by heosman** [comment]
@ken-ni When we switched to MUI, we were moving away from using the stylesheets, and the Home page and Event details pages were the only pages that were using them at that point. It was also much easier to manipulate the pages to be responsive with inline styling.

**Review by intisarosman1 — COMMENTED** [review]
The page looks great on all screen sizes but I noticed that the size of the upcoming events increases based off  of how many events exist and gets wider. Originally, the single event isn't very wide.
Screenshot 2024-07-12 194421
Screenshot 2024-07-12 194452
Screenshot 2024-07-12 195930

**Comment by heosman** [comment]
@intisarosman1 I set a minimum width so the event card will be at least 460 px wide. It looks better now when there are less events, but it would start to break if I made it any wider than this.

image

**Comment by intisarosman1** [comment]
> @intisarosman1 I set a minimum width so the event card will be at least 460 px wide. It looks better now when there are less events, but it would start to break if I made it any wider than this.
> 
> image

Looks better now!
image

**Review by intisarosman1 — APPROVED** [review]

**Pull request merged**
