### PR TITLE
Modification package.json

### PR DESCRIPTION
**Pull request by miqo1385**
nsc-events-nextjs _  sprint13  _  updating-dependencies

Resolves issue #559 
Description of what this pull request is for.

deleting carets from package.json

### CODE REVIEW

**Comment by Diego-Cano** [comment]
This pull request addresses updates to package.json, specifically removing carets to lock versions and make sure consistency across installations. The dependency updates also required a review of functionality due to some minor issues with public images, which have been corrected.

After pulling the branch, I ran the tests locally and confirmed that all 13 tests across 6 test suites passed successfully. There was a warning related to the punycode module being deprecated and a couple of minor issues with image components missing a src attribute. These warnings don’t affect functionality but may be worth addressing in a future PR for cleaner output. This update is a step in the right direction for maintaining a stable codebase. For more guidance on managing dependencies effectively, check out this page: [Dependency Management: Protecting Your Code.
](https://www.mend.io/blog/dependency-management-protecting-your-code/) 

Screenshot 2024-10-27 at 11 09 02 AM

**Comment by gitbiruk2010** [comment]
@miqo1385 seems like there is a compiling issue coming from image references /couldn't find module when i run it from my end. I would look into changing the image references for the program to compile with no errors. otherwise, versions look compatible and utd.

**Comment by bennettsf** [comment]
Is this not the same PR from the dependencies branch/PR from the past few weeks? All of the changes here look like they're already merged to main from that previous PR so I'm not to sure what this is for.

**Review by el-riber — APPROVED** [review]

**Review by bennettsf — CHANGES_REQUESTED** [review]
Is this not the same PR from the dependencies branch/PR from the past few weeks? All of the changes here look like they're already merged to main from that previous PR so I'm not too sure what this is for. The carats have already been taken care of :smile:

**Pull request closed without merging**
