### PR TITLE
nsc-events-nextjs-7-351-display-archived-events

### PR DESCRIPTION
**Pull request by cshimm**
### This PR depends on SeattleColleges/nsc-events-nestjs#118. Please check out branch `refactor-118-update-getAllActivities-service-method` in the nsc-events-nestjs repo when testing this PR.

Displays 5 archived events with pagination.

https://github.com/SeattleColleges/nsc-events-nextjs/assets/13278479/53a092be-72e4-4ea8-bbae-9a955d0bc000

### CODE REVIEW

**Comment by bennettsf** [comment]
Is it showing non-archived events for you? For some reason it is for me, however the pagination works well. 
fGcuB3W

**Review by bennettsf — APPROVED** [review]
fixed the issue on my end, works as described!

**Comment by Ali-7s** [comment]
Not sure if it's just on my end but it duplicates the archived events and throws an error when I archive one but it goes away on refresh. Other than that it works well

https://github.com/SeattleColleges/nsc-events-nextjs/assets/22021615/03bbb433-75c3-43db-9d75-e1a75b367db4

**Comment by cshimm** [comment]
@Ali-7s Are you on the "refactor-118-update-getAllActivities-service-method" branch in the nestjs repo?

**Comment by Ali-7s** [comment]
> @Ali-7s Are you on the "refactor-118-update-getAllActivities-service-method" branch in the nestjs repo?

Yeah
image

**Comment by cshimm** [comment]
@Ali-7s Ok thanks. Thats a pretty weird bug so I'll take a look into what might be causing that.

**Comment by cshimm** [comment]
@Ali-7s Thank you for pointing that bug out to me. I think I found a fix. Can you test again to make sure it's squashed on your end as well?

**Review by taylorpapke — APPROVED** [review]
Works for me:
Screenshot 2024-05-26 at 2 21 48 PM
Screenshot 2024-05-26 at 2 22 02 PM

**Comment by Ali-7s** [comment]
> @Ali-7s Thank you for pointing that bug out to me. I think I found a fix. Can you test again to make sure it's squashed on your end as well?

Works well for me now!

**Review by Ali-7s — APPROVED** [review]
LGTM!

**Review by intisarosman1 — APPROVED** [review]
I archived an events and was able to see it on the archived-events page.
Screenshot 2024-05-26 232848

**Review by heosman — APPROVED** [review]
Looks good to me!
image

**Comment by nwm516** [comment]
Wonderful! I was also able to replicate similar results with my Archived Events. LGTM.

Archived Events

**Pull request merged**
