### PR TITLE
nsc-events-nextjs-10-551-add-document-field

### PR DESCRIPTION
**Pull request by Ali-7s**
Satisifes #551
PR adds the event document field in the create event form
* Added eventDocument field to models
* Added event document text field in the create event form
* Added validation for event document field

https://github.com/user-attachments/assets/a924a584-1d11-49ce-b912-a3c55556e3a6

### CODE REVIEW

**Review by bcko — APPROVED** [review]
Great job, let's get this merged

**Review by heosman — APPROVED** [review]
The document field has been added to the Create Event page and I am able to create an event successfully.

image

**Comment by alasali1** [comment]
Looks good to me.

**Review by alasali1 — APPROVED** [review]
Looks good to me

**Pull request merged**
