### PR TITLE
nsc-events-nextjs_7_432_role-authorized-archived-events-2

### PR DESCRIPTION
**Pull request by taylorpapke**
#432 

Role Authorized update

### CODE REVIEW

**Review by heosman — APPROVED** [review]
Works great, I'm unable to access the Archived Events page as a user and when not signed in.

**Review by nwm516 — APPROVED** [review]
I was able to create a user with basic access (non-admin) and was shown the 401 Unauthorized Access. That part LGTM. 

Something else I did notice was that the "Sign In" button as a basic user does not change to "Sign Out" after logging in. I spent a little too much time troubleshooting on my end before I realized that I had access... That's beyond the scope of this user story but something worth noting. 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/36825393/2fe61d41-5e84-4942-b48f-dd3574e0923d

**Comment by heosman** [comment]
> I was able to create a user with basic access (non-admin) and was shown the 401 Unauthorized Access. That part LGTM.
> 
> Something else I did notice was that the "Sign In" button as a basic user does not change to "Sign Out" after logging in. I spent a little too much time troubleshooting on my end before I realized that I had access... That's beyond the scope of this user story but something worth noting.
> 
>  User.Authorized.Access.mp4

@nwm516 Did you make sure to pull origin on this branch? I recently fixed the SIgn Out button issue in another PR and it's been merged to main, so it should be working now.

**Comment by nwm516** [comment]
> > I was able to create a user with basic access (non-admin) and was shown the 401 Unauthorized Access. That part LGTM.
> > Something else I did notice was that the "Sign In" button as a basic user does not change to "Sign Out" after logging in. I spent a little too much time troubleshooting on my end before I realized that I had access... That's beyond the scope of this user story but something worth noting.
> > User.Authorized.Access.mp4
> 
> @nwm516 Did you make sure to pull origin on this branch? I recently fixed the SIgn Out button issue in another PR and it's been merged to main, so it should be working now.

@heosman Ah yep, my mistake. Everything is as it should be! LGTM!


https://github.com/SeattleColleges/nsc-events-nextjs/assets/36825393/19963697-b8a8-459a-bbaf-ff367c8a543d

**Review by intisarosman1 — APPROVED** [review]
I can see the Archived Events page's contents while logged in as an admin, but when I log out, I'm presented with an Unauthorized 401 error message, as it should!
Screenshot 2024-06-09 215333

**Pull request merged**
