### PR TITLE
nsc-events-nextjs-01-119-modify-frontend-port

### PR DESCRIPTION
**Pull request by Robel-003**
Relates to user story #119 

This pr creates an example .env with the proper environment variables and values. The frontend .env variable for the url is set to http://localhost:3001. The MONGO_URI is just an example of a value but one would need to capture that connection string value after creating a database instance or if one already exists, you can just grab that connection string and add it as the MONGO_URI value. Here is a quick demonstration of the steps https://youtu.be/Ye28mc1Ipy8

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
LGTM. This will definitely help people who need to get their connection set up.

**Review by Exochos — APPROVED** [review]
This should help new developers get up to speed easier!
LGTM

**Comment by tinpham5614** [comment]
I just noticed that the .env file is just helping us for now, but later we might not need it because we will fetch API endpoints from the backend to capture data.

**Comment by Exochos** [comment]
> I just noticed that the .env file is just helping us for now, but later we might not need it because we will fetch API endpoints from the backend to capture data.

Yeah, we should make a note to make sure to remove this with the release version of the app

**Pull request merged**
