### PR TITLE
nsc-event-nextjs_6_285_nav-bar-modifications

### PR DESCRIPTION
**Pull request by miqo1385**
This is a pull request!

Please fill out this description with the following:
Resolves <issue #285 >

https://github.com/SeattleColleges/nsc-events-nextjs/assets/97195623/d1bb61a9-3706-4471-9a21-07e213c3354e

### CODE REVIEW

**Review by JesseCaddell — APPROVED** [review]
image
drop down menu working as intended!

I had a bit of trouble finding this branch, figured it was nsc-event-nextjs_6_285_nav-bar-modifications but it was actually NavBar-updates.

**Review by Ali-7s — APPROVED** [review]
LGTM
image

**Review by heosman — CHANGES_REQUESTED** [review]
There's a few changes that need to be made here.

1. The "Account" and "Dashboard" buttons in the profile dropdown menu can be removed, as they're not needed for NSC Events. The "Logout" button should say "Sign Out". The "Events" link should remain to the left of the profile dropdown menu on the right side of the nav bar.
2. The icon for the profile dropdown should be using the [MUI account circle icon](https://mui.com/material-ui/material-icons/).
image

3. I see you've made some changes on the left side of the nav bar, however, no such changes were requested in your user story. It would be best if you restored this section of the nav bar to its previous state.
image

4. Thie profile dropdown should only be visible to admins and creators. There should be no changes to the nav bar (should look the same on the main branch) if the user is a normal user or the user is not signed in.

This is what the right side of the nav bar looks like on the main branch when not signed in:

image

This is what the right side of the nav bar looks like on the main branch when signed in as a user:

image


5. Clicking the "Profile" button in the profile dropdown menu should be routing admins to the Admin page, and creators to the Creator page. I'm not sure if you will address this in this PR or another issue.

Here's a mock up that should help:
nav bar mockup



You should also address the branch conflicts.

**Comment by kaimanasse15** [comment]
Looks great!
image

**Comment by MuhammadNSC** [comment]
Adding a profile icon is a great addidtion to NSC. Additionally i like the NSC printed name that was added to the top left of the Navbar. I will recommend to replace the android icon with the NSC school logo. 
Before:
Screenshot 2024-05-30 at 11 41 20 AM
After:
Screenshot 2024-05-30 at 11 32 20 AM

**Review by alasali1 — APPROVED** [review]
It looks great to me. The user icon creates a cleaner and more professional appearance to the UI.

**Pull request closed without merging**
