### PR TITLE
nsc-events-08-436-bug-create-new-event-required-field-logic-fix

### LINKED ISSUE #436: Bug: Missing requirements for creating new event stay visible after corrected
When creating a new event if you do not fill the required boxes you are presented with red text telling you what you need to complete. When you correct those errors, they stay on the screen even after the event is successfully created.

Adding additional issue noticed within the same bug. Event Privacy is required and you get a prompt that it should not be left empty, yet there is no red outline around Event Privacy and no red text saying Event Privacy is required.

Additional notes via Hanan:
I also noticed that some fields are optional but still require you to fill out the field and vice versa (like Event Note). The error handling for all of the fields should match on the frontend and the backend. 

**To Reproduce**\
Create an event
Leave fields blank
Once red text shows up, complete all required forms
Click create event

**Expected behavior**\
Red text should disappear when the form required is corrected

**Screenshots**\
red text not veing removed
image
Event Privacy
image

**Desktop (please complete the following information):**\
 - OS: Windows
 - Browser: Firefox
 - Version 126.0.1

**Is this issue related to any other issues?**\
Not that I am aware of

**Story Points**\
maybe 2

### PR DESCRIPTION
**Pull request by cshimm**
Resolves #436 
This PR resolves the issue where the required field error persists even after the user fills in the field with the appropriate data.
 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/13278479/cf30052e-aede-46b8-8ec6-5540f67ab0a5

Also here is a list of errors that don't appear as required field errors (the text fields aren't highlighted red) until clicking Submit. Adding the required field errors for these fields would be a different issue but once added, this PR should properly handle the required field errors once implemented. 
image

### CODE REVIEW

**Review by heosman — COMMENTED** [review]
@cshimm The errors for the Event Cover Photo and Event Meeting URL fields still persist even after filling them out, which prevents me from creating an event.
image
image

**Comment by cshimm** [comment]
@heosman I fixed the URL bugs with a URL regex pattern. It works but it might be better to use a library like 'validator' that does more robust form validation and is easier to read and use—just a thought.

**Review by heosman — APPROVED** [review]
Looks good now! Once the required fields are filled in, the errors disappear.

**Review by intisarosman1 — APPROVED** [review]
Works as it should!

https://github.com/SeattleColleges/nsc-events-nextjs/assets/77607212/d40c8c3a-af2c-4da8-b489-931f62cf567d

**Pull request merged**
