### PR TITLE
NSC-Events-Nextjs-7-402-unit-test-sign-in-page

### LINKED ISSUE #402: Unit Test: Sign-in Page
- [x] This unit test is meant to test the functionality of the sign in page

### PR DESCRIPTION
**Pull request by MaddasaHatter**
Resolves #402 
- [ ] This PR resolves the issue of creating a unit test for the sign in page so that we can test to ensure the primary functions of the page are working.

### CODE REVIEW

**Review by Seiyaroo — APPROVED** [review]
LGTM, is the intellisense stuff something we should remove or does it matter?

**Review by taylorpapke — APPROVED** [review]
I did an npm install to get next-router-mock and the test passed:
Screenshot 2024-06-04 at 10 34 03 PM

**Comment by tinpham5614** [comment]
Do we need the .vscode launch file to be merged into the main branch?

**Comment by MaddasaHatter** [comment]
I don't think I updated the launch file. It might be some weird white space thing if there is a change to that file.

**Review by keiffer213 — APPROVED** [review]
Looks great! The test passed for me, thanks @taylorpapke for mentioning to do an npm install since I was getting a failed test at first

image

**Comment by heosman** [comment]
@MaddasaHatter It seems the .vscode directory is not necessary so if you could delete it from your branch, and commit and push that change, we can merge this PR.

**Review by heosman — APPROVED** [review]

**Review by intisarosman1 — APPROVED** [review]
The tests pass, LGTM!
Screenshot 2024-06-06 232852

**Pull request merged**
