### PR TITLE
nsc-events-nextjs_5_306_testing-creator

### PR DESCRIPTION
**Pull request by kaimanasse15**
relates to #306 
I have a problem with the mock issue

### CODE REVIEW

**Comment by taylorpapke** [comment]
It looks like the testing-button branch was created from one of @Bejarano03's branches that has yet to be merged. My concern is that we will see merge conflicts if we go this route. Can we let @Bejarano03 get his branch merged with the jest install and a couple unit tests so you can just create a new branch from main and write your tests?

**Comment by kaimanasse15** [comment]
@taylorpapke, I wondered if his part has merge on the main as you said yet?

**Comment by taylorpapke** [comment]
@kaimanasse15 Not yet, I believe we will be making a decision tonight regarding testing.

**Comment by taylorpapke** [comment]
@kaimanasse15 This is going to be a hard one to fix. Should we just close it and make a new PR?

**Comment by kaimanasse15** [comment]
@taylorpapke  Yes! Please help me to close it. I created another one the test look good. However, I need to see Marco tomorrow to dicuss a little bit. I will commit the new creator test tmr. Thanks, Taylor

**Pull request closed without merging**
