### PR TITLE
nsc-events-nextjs_7_continuous-deployment_add-ssh-workflow

### LINKED ISSUE #416: Continuous Deployment: Deploy code to production through SSH.yml
Relates to https://github.com/SeattleColleges/nsc-events/issues/48.
As a developer, I want a workflow that pulls the updated code from the main branch and refreshes the website with PM2 to the EC2.

### PR DESCRIPTION
**Pull request by TuongPhamM**
resolves #416 

This workflow has been tested in [my fork](https://github.com/TuongPhamM/nsc-events-nextjs/actions/runs/9374797733).
Here is the run showing passed secret key, Node and Branch update.

https://github.com/SeattleColleges/nsc-events-nextjs/assets/77989401/fd0a13c5-84c7-419c-9d98-8b5757b1a834

### CODE REVIEW

**Review by tinpham5614 — APPROVED** [review]

**Review by taylorpapke — APPROVED** [review]
Looks good to me

**Review by heosman — APPROVED** [review]
LGTM!

**Review by intisarosman1 — APPROVED** [review]
The deployment was successful. LGTM!

**Comment by heosman** [comment]
@brinkbrink Can this be merged without the check being completed?

**Pull request merged**
