### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by Seiyaroo**
This is a markdown example template, attempting to follow guidelines below for template creation for future usage.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

### CODE REVIEW

**Review by theGaryLarson — APPROVED** [review]
Looks good. Thanks, I was wondering how to mark that I had added .idea to the gitignore on my first PR. I like that because it helps call out things that might slip through the cracks.

**Comment by taylorpapke** [comment]
Looks good to me. Do you want reviews turned on for the rest of the team?

**Review by taylorpapke — APPROVED** [review]

**Comment by Seiyaroo** [comment]
> Looks good to me. Do you want reviews turned on for the rest of the team?

I don't mind them turned on for rest of the team. I personally don't mind all the notifications as I tend to check all the PR's out so I have an idea of what's going on where. But I know not everyone is as attentive intentionally.

**Review by brinkbrink — APPROVED** [review]
Awesome work! Thank you for getting this done. The verbiage is also very clear and I like the way it's set up with pictures in case people need the visual. 

I would just delete line 3 once this is merged into main. 

I would also like to make sure @tinpham5614 and @Robel-003 review to give input. I would really like everybody to be involved in giving feedback since it will affect everybody.

**Comment by bcko** [comment]
Thank you for creating a pull request template!

**Review by bcko — APPROVED** [review]

**Review by brinkbrink — COMMENTED** [review]
Oh and I would highlight the last point about Resolves #<issue number> instead of having at the end as extra info. It's something our TPM has stressed as important and is really helpful since it will automatically status the issue for us. Maybe include the why (that it statuses the issue automatically) so people only put "resolves" if it is ready to be statused as complete.

**Review by brandondombrowsky — APPROVED** [review]
I like this a lot! I only have a few minor polishes on text but nothing to hold up approval.

**Pull request merged**
