### PR TITLE
nsc-events-06-290-Event-Card-Component

### LINKED ISSUE #290: Create a card component that can be reused within the project

### PR DESCRIPTION
**Pull request by bennettsf**
Resolves #290 

This PR refactors pages that map out events (Homepage, View My Events, etc.) with the addition of the EventCard component. With this new component we will be able to avoid duplicate code, have more efficient styling, and have improvements to the overall organization of our code.

Testing: 

Testing for this PR is as simple as running the project locally and making sure the new component is functioning as expected. Reviewers can focus mainly on the code changes, as you can see I was able to remove duplicate code from `HomeEventGetter.tsx` and `ViewMyEventsGetter.tsx` using the new component.

Screenshot of refactored code:
EventCardRefactor

### CODE REVIEW

**Comment by cshimm** [comment]
The card looks great. I tested on my local machine and everything behaves the same way as before. Nice job!

I'm wondering if we should maybe avoid committing changes to next.config.js to avoid confusion. Is there any way to remove the change from the PR?

**Comment by MaddasaHatter** [comment]
The cards look great. It's an excellent idea to reduce redundancy to improve overall efficiency and reduce the potential for bugs and other issues.


https://github.com/SeattleColleges/nsc-events-nextjs/assets/52189566/106290f5-1c30-4d39-8914-d2d9277f83ed

**Review by cshimm — APPROVED** [review]

**Review by JesseCaddell — APPROVED** [review]
Looks great and much easier to read. I ran it locally and encountered zero errors. Great job!

**Review by taylorpapke — APPROVED** [review]
New component looks and works fine. No problems encountered while testing.

**Pull request merged**
