### PR TITLE
nsc-events-nextjs_8_427_edit-dialog-arrows

### LINKED ISSUE #427: Event Detail Page 2: Edit dialog box and arrows
As a developer, I will want to decrease the width of the edit dialog box (when editing event) and add subtle shadow to the arrow icons (so that arrows can be visible on backgrounds of all colors).

### PR DESCRIPTION
**Pull request by intisarosman1**
Resolves #427

This PR changes the edit dialog box on the Event Detail page to be less wider. Drop shadow has been added to the arrow icons so they stand out better from the background.

Before
Screenshot 2024-06-05 012651
After
Screenshot 2024-06-05 012714

Before
Screenshot 2024-06-05 012540
After
Screenshot 2024-06-05 012621

### CODE REVIEW

**Review by heosman — APPROVED** [review]
Looks good, shadow was added to arrow icons and the edit dialog is less wide.

image

**Comment by MuhammadNSC** [comment]
This PR works as explain and looks good. Event dialog window is minimize a little and the edit box is shaded in grey.

**Comment by gitbiruk2010** [comment]
This PR looks good on my end!

**Comment by Diego-Cano** [comment]
Hey team,

I checked out the pull request for the Event Detail page changes. The update to the edit dialog box and arrow icons look awesome! Making the edit dialog box narrower definitely helps it look cleaner and easier to navigate. Adding the drop shadows to the arrow icons really makes them pop against different backgrounds, which is a nice touch since it gives it a contrast with the rest of the UI.

Looking at the file changes, I noticed you applied the drop shadow to both the back and forward arrow icons, and the dialog box adjustments seem good. The updated edit dialog box looks much better with these additions. One suggestion would be to make sure the shadows are consistent across all pages and screen resolutions to keep the UI looking cutting edge.

I found a helpful guide on improving UI with shadows and depth:
https://bootcamp.uxdesign.cc/designing-in-the-shadows-how-to-use-shadows-to-enhance-your-ui-72cda79aa878

Thanks!

**Review by TuongPhamM — COMMENTED** [review]
Looks great! I these adjusted significantly will improve user's experience. I be nit picky, the buttons of the event box are too close to the edge, maybe add more padding on the left and right?

**Comment by miqo1385** [comment]
I can see that in my end, it looks wonderful.

**Review by Ali-7s — APPROVED** [review]
LGTM!
Edit dialog is less wide than before and shadowing of arrows looks good
image
image

**Pull request merged**
