### PR TITLE
 nsc-events-nextjs_6_341_unit-test-for-event-detail-page

### PR DESCRIPTION
**Pull request by kaimanasse15**
This is the Unit test for Event-detail Page

Issue: #341

### CODE REVIEW

**Comment by kaimanasse15** [comment]
I have an error with this part and still not figure out yet.
image

**Comment by MuhammadNSC** [comment]
Not all the tests passed. I did a bit of research to see what the issue here might be and to my knowledge i think to resolve this issue, you need to mock the Next.js router in your test. This can be achieved using jest.mock to create a mock implementation of the useRouter hook. Other classmates might have better solutions to help fix the issue
Screenshot 2024-05-21 at 2 20 32 PM

**Comment by brinkbrink** [comment]
@kaimanasse15 Did you try @MuhammadNSC's advice?

**Comment by kaimanasse15** [comment]
> @kaimanasse15 Did you try @MuhammadNSC's advice?
It doesn't work for me. I think I need someone else to follow this. Thanks, @brinkbrink

**Comment by MaddasaHatter** [comment]
It's still failing were you able to try other resources for this?

Screenshot 2024-06-03 173056

**Comment by taylorpapke** [comment]
Closing due to inactivity. Reopen if needed.

**Pull request closed without merging**
