### PR TITLE
nsc-events-nextjs-5-264-view-my-events-page

### LINKED ISSUE #264: View My Events Page: Create a page that displays events created by the user that is signed in (only for admins & creators)
relates to #251

### PR DESCRIPTION
**Pull request by bennettsf**
Resolves #264

This PR creates a "View My Events" page for Admins/Creators to view the events of the currently logged-in user. I also added a redirection to that page from the 'View My Events" button on the admin/creator dashboard.

### Testing Instructions:
1. Have your backend properly set up. 
- Make sure to comment out `NSC_EVENTS_PUBLIC_API_URL: "https://northseattlecollegeevents.com/api"`, on line 6 of the `next.config.js` file. Otherwise you will be making requests to the production database and it won't let you into your personal DB!
2. Make sure your nsc-events-nestjs backend is on the correct branch!
- Until [#107](https://github.com/SeattleColleges/nsc-events-nestjs/pull/107) is merged, you will need to use `git checkout feature-106-user-events-API-endpoint-01`
3. Create two admin/creator accounts if you haven't and make sure each one has created one or two test events.

4. Once everything is set up, head over to the dashboard on each account and click "View My Events" to see the events you created on the currently logged-in account.

https://github.com/SeattleColleges/nsc-events-nextjs/assets/33855430/ad05874e-2ad5-4e6f-bcfb-18c03d4281b2

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks good.
Admin My Events:
Screenshot 2024-04-22 at 2 08 05 PM
Creator My Events:
Screenshot 2024-04-22 at 2 11 24 PM

@heosman Creator Page "View My Events" button does not link to http://localhost:8080/my-events but can probably be taken care of in the next sprint

**Comment by cshimm** [comment]
Looks good. Like @taylorpapke said, the View My Events button on the creator page doesn't do anything but that's an easy fix. The core functionality works as expected. I tested with an admin and creator account and a different list of events was displayed for each.

The app crashes when clicking the event to go to its event details page, but this should be resolved once #275  is merged.

**Review by brinkbrink — APPROVED** [review]
This is working as expected, even the "View my Events" button! Thanks for adding that quick fix to this PR. Also, thanks for the detailed PR description with video. Very helpful for speedy reviewing!

**Comment by brinkbrink** [comment]
Hey @bennettsf  I'm merging without waiting for requirements to be met--the only missing requirement here is unsigned commits. This thread is pretty helpful and covers both SSH and GPG. You can use either...or both! I also recommend to look into auto-signing your commits. Once you set up your key you either have to remember to sign (pretty sure with an -S) or auto-sign your commits. This seems to be something that trips people up, including me when I first learned about signing commits.

**Comment by brinkbrink** [comment]
I just left a hopefully helpful comment to deal with that failing CodeFactor test on that PR.

**Pull request merged**
