### PR TITLE
nsc-events-nextjs-256-archive-functionality

### PR DESCRIPTION
**Pull request by Ali-7s**
* Created ArchiveDialog component with functions for archiving event
* Added isArchived to activityDatabase

https://github.com/SeattleColleges/nsc-events-nextjs/assets/22021615/40a624e6-04e4-4bec-b8fe-53e5c7e79ad1

### CODE REVIEW

**Review by Seiyaroo — APPROVED** [review]
This looks awesome Ali, well done!

**Review by taylorpapke — CHANGES_REQUESTED** [review]
So, I tested this PR and it is working as far as archiving events on the frontend and making the proper changes to the data on the backend:
Screenshot 2024-04-18 at 1 02 38 AM

However, I am running into an issue with creating events now. When I create an event, it will not display on the home page. I tested main and it is working so I think it might have to do with some of the changes that were made to HomeEventGetter.tsx or UpcomingEvent.tsx components. @keiffer213

**Comment by heosman** [comment]
I'm experiencing the same thing as @taylorpapke. I am able to archive the event successfully, the event is hidden on the frontend, and the backend is updated. I didn't create new events, but I do have other events that I have had for a while and they are not displaying even when there are less than 5 events visible. I think the other events not showing up may have to do with what we talked about with BC last quarter: how the events being displayed are limited to 5 events, except the deleted and archived events are still in the database but hidden, so our other events including new ones won't show up. I could be wrong though.

@cshimm Are you also running the backend using this [PR](https://github.com/SeattleColleges/nsc-events-nestjs/pull/101) at the same time with this PR?

**Comment by Ali-7s** [comment]
> So, I tested this PR and it is working as far as archiving events on the frontend and making the proper changes to the data on the backend: Screenshot 2024-04-18 at 1 02 38 AM
> 
> However, I am running into an issue with creating events now. When I create an event, it will not display on the home page. I tested main and it is working so I think it might have to do with some of the changes that were made to HomeEventGetter.tsx or UpcomingEvent.tsx components. @keiffer213

As Hanan said there's a 5 event limit thats fetched from the backend, when we call archive we're only hiding the event on the frontend and adding any more then 5 won't show on the frontend unless we delete any of the first 5 from the database.

**Comment by cshimm** [comment]
I got it working, thanks for the info @heosman

**Review by heosman — APPROVED** [review]

**Comment by heosman** [comment]
@Ali-7s @taylorpapke Let's get this PR reviewed and merged, and then address the 5 event limit in another issue. I'll add it to the product backlog for now.

**Review by brinkbrink — APPROVED** [review]
I am approving this review at the request of the product owner. The user story requirements are fulfilled with this pull request. The five event functionality will be addressed in the next sprint.

**Pull request merged**
