### PR TITLE
nsc-events-nextjs-5-50-finish-web-user-auth

### PR DESCRIPTION
**Pull request by taylorpapke**
resolves: https://github.com/SeattleColleges/nsc-events-nextjs/issues/50

to test:
- create a Mongo DB database and create a database and collection
- create a .env file under project folder (same level as .env.sample) and add the following:
MONGODB_URI=<your Mongo DB connection string w/ database and collection appended to the end>
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=secret
Screenshot 2023-08-10 at 1 55 43 PM
Screenshot 2023-08-10 at 1 52 53 PM

- remember to replace <username> and <password> with your actual username and password from mongodb when you created your cluster.

other notes:
- use login page to login (home page login not currently working)
- you have to hover over logout (not the name next to it) to logout

### CODE REVIEW

**Review by tinpham5614 — COMMENTED** [review]
- Tested and it works.
- Database retrieved data from the signup page.
- The login function works:
  - if - We input the matching information
  - else - nothing happens at the moment.
- The logout function works.
- My question: 
What page the user be redirected to after successfully logging in?

The UI is hard to see at the moment, but I will work on it with issue #47 after this PR is merged.

**Review by theGaryLarson — CHANGES_REQUESTED** [review]
LGTM but uncomment the router replace method on L44 in app/api/auth/sign-in/page.tsx. Also, use an if else statement there so it doesn't navigate to the profile page on error. 
@tinpham5614  I believe this may give some insight to your question regarding which page successful login directs to.

**Comment by theGaryLarson** [comment]
@tinpham5614 Here is the pdf of NSC Events Mobile. I'm thinking matching the flow of the web app to the mobile would be ideal, so I think this will work for illustrating routing.
[NSC Events Mobile.pdf](https://github.com/SeattleColleges/nsc-events-nextjs/files/12328507/NSC.Events.Mobile.pdf)

**Review by Robel-003 — APPROVED** [review]
This looks good! I'm able to sign-up and see my registration info in the db. I'm also able to login and be routed "profile" page.

**Review by theGaryLarson — APPROVED** [review]

**Pull request merged**
