### PR TITLE
nsc-events-nextjs-9-508-archived-event-detail-page-doesnt-load

### LINKED ISSUE #508: BUG: Fix "Loading..." when clicking an event that is archived
When an event on the Archived Events page is clicked, the user is routed to the Event Detail page, but the event card is not rendered.

image

### PR DESCRIPTION
**Pull request by cshimm**
resolves #508 

Now you should be able to view the event detail page from any page that displays a list of events (home page, archived events, my events)

It should be noted that only the events that were loaded on the page before clicking an event can be accessed via the next and previous buttons. This was the behavior before this fix. I think I could implement a way to cycle through all of the events of each category via the event detail page in a separate issue if necessary. 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/13278479/ad942c01-df00-4946-bebe-68b311a99f1f

### CODE REVIEW

**Review by heosman — APPROVED** [review]
That fixed the bug, I am able to navigate to the event detail page for archived events now. Thank you for working on this!

image

**Comment by ken-ni** [comment]
Hello @cshimm, I'm trying to test your changes on the branch but for some reason I'm getting a CORS error and I can't login nor are any of my events loading:
login
error
Do you have any idea what could be causing this? I would like to test your awesome changes!

**Comment by cshimm** [comment]
hi @ken-ni I believe that the problem may be specific to your local machine's configuration. Can you provide what your next.config.js file looks like? You need to either run the server locally or have the line ` NSC_EVENTS_PUBLIC_API_URL: "https://northseattlecollegeevents.com/api",` uncommented out.

**Review by intisarosman1 — APPROVED** [review]
I am able to see the event detail pages of archived events now with no problem. LGTM!
Screenshot 2024-07-07 164650

**Review by ken-ni — APPROVED** [review]
After testing the changes on your branch today, I didn't have anymore issues. Maybe something was down when I was testing yesterday? Anyways, looks good to me! Archived events can now be viewed and my events/homepage work fine too.

https://github.com/SeattleColleges/nsc-events-nextjs/assets/60593178/e3963994-a8c7-4d6b-afff-df8033066f07

**Pull request merged**
