### PR TITLE
nsc-events-nextjs-7-397-clean-up-error-msgs

### LINKED ISSUE #397: Refactor: Clean up error messages on Create Event page
- Relates to #396 
- [ ] Clean up error messages for all fields on the Create Event page

### PR DESCRIPTION
**Pull request by ken-ni**
Resolves #397 

Adds more descriptive error messages when creating events

### CODE REVIEW

**Comment by heosman** [comment]
@ken-ni The branch for this PR is behind, you need to resolve the branch conflict so that you can pull the recent changes from the main branch.

**Comment by ken-ni** [comment]
@heosman Thank you for the feedback! I was able to resolve the branch conflict and merge main into this branch I think.. Let me know if I did it incorrectly.

**Review by intisarosman1 — APPROVED** [review]
The error messages sound more descriptive! LGTM
Screenshot 2024-06-29 232405

**Comment by cshimm** [comment]
LGTM
image

**Review by cshimm — APPROVED** [review]

**Comment by nhapham03** [comment]
LGTM

**Pull request merged**
