### PR TITLE
nsc-events-nextjs_2_167_creator-page-buttons

### LINKED ISSUE #167: Creator Page: Add Buttons
As a developer, I'd like to have a creator page where there is an "Edit User Role" button, "Create Event" button, and "View Event" button, with the "Create Event" button redirecting to Create Event page.

Related to User Story #166

### PR DESCRIPTION
**Pull request by intisarosman1**
Resolves #167 

I created a "Create Event" button, "View My Events", and "View All Events" button for the creator page. The "Create Event" button redirects to the Create Event page.

I added basic CSS styling to match the style of the web app's Home page, with NSC Events theme colors for the buttons (like the android app's AdminView page).

Screenshot 2024-02-05 061314

Related to User Story #166

### CODE REVIEW

**Review by taylorpapke — CHANGES_REQUESTED** [review]
Small copy/paste error I'm assuming here but we will need to remove the edit user role button since this is the creator page and only admins have that ability. Everything else is looking good other than that and logging in as a creator brought me to this page.

**Comment by intisarosman1** [comment]
> Small copy/paste error I'm assuming here but we will need to remove the edit user role button since this is the creator page and only admins have that ability. Everything else is looking good other than that and logging in as a creator brought me to this page.

Sorry about that! I've corrected the issue and made the appropriate changes for the buttons (see image above).

**Comment by taylorpapke** [comment]
Looks good to me. @heosman I didn't realize until now that we were also doing a "view my events" button. Why isn't this included in the admin page as well if this is a feature the client wants?
Screenshot 2024-02-05 at 3 08 30 PM

**Review by taylorpapke — APPROVED** [review]

**Comment by heosman** [comment]
> Looks good to me. @heosman I didn't realize until now that we were also doing a "view my events" button. Why isn't this included in the admin page as well if this is a feature the client wants? Screenshot 2024-02-05 at 3 08 30 PM

@taylorpapke @intisarosman1 I was referencing the android version of the app, but yes, we should add an additional button on the admin page for viewing the events that the admin has created. We should probably do the same for the android app too.

**Review by heosman — APPROVED** [review]
The page looks great!

**Pull request merged**
