### PR TITLE
nsc-events-nextjs-5-318-create-page-and-components

### LINKED ISSUE #318: Edit User Role Page: Create page and components
relates to #317 

This issue is for adding the page along with a couple of the components that are used.

### PR DESCRIPTION
**Pull request by taylorpapke**
resolves #318 

This PR attempts to add the edit-user-role-page along with some components that are used in it.

### CODE REVIEW

**Comment by taylorpapke** [comment]
@tinpham5614 This PR is an attempt to carry over the edit-user-role-page and its components from Belinda's Closet. It is not displaying user's card for some reason. Do you have any idea why this is not working?

**Comment by tinpham5614** [comment]
The result after fixing bugs should be something like these:
1. The edit role page UI:
edit role page
2. Successful change the user role:
successful edit role

**Review by alasali1 — CHANGES_REQUESTED** [review]
On my end I am getting a 401 unauthorized error when trying to GET the user info.
I think it might have something to do with the bearer token?
image
image

**Comment by tinpham5614** [comment]
Did you login using an admin account?

**Comment by taylorpapke** [comment]
Page appears to be working now with @tinpham5614's changes:
Screenshot 2024-05-05 at 3 12 10 AM
Change role from user to creator:
Screenshot 2024-05-05 at 3 12 39 AM
Screenshot 2024-05-05 at 3 13 27 AM

**Review by heosman — APPROVED** [review]
After navigating to the edit user role page on an admin account, I was able to change the role of a user. 

image

**Comment by MuhammadNSC** [comment]
This is how my edit user role screen looks like. It just shows Management on the scree.
Screenshot 2024-05-08 at 6 55 52 PM

**Comment by taylorpapke** [comment]
@alasali1 Can you re-review and approve if it is working now?

**Review by Ali-7s — APPROVED** [review]
LGTM! Wasn't able to access the cards on a user account but I was able to change the role then access it
image

**Review by intisarosman1 — APPROVED** [review]
I am able to successfully edit the role of users and the change registers in the database. 
Screenshot 2024-05-10 051039

**Review by IsaacJrTypes — APPROVED** [review]
Looks awesome! I was able to change roles to the user without issues. 
CleanShot 2024-05-10 at 12 18 31@2x
CleanShot 2024-05-10 at 12 19 33@2x

**Pull request merged**
