### PR TITLE
Delete signup-page.module.css

### LINKED ISSUE #177: USER STORY: Signup Page
As a developer I would like to clean up various parts of the signup page:
- [x] #179
- [x] #182
- [x] #183
- [x] #184
- [x] #185
- [x] #186
- [x] #187
- [x] #188
- [ ] #189

- [x] Other issues?

### LINKED ISSUE #179: Removed unused CSS_module
Relates to #177

### PR DESCRIPTION
**Pull request by Exochos**
Deleted unused CSS module. 
After the refactor to MUI we have various unused CSS modules in the codebase, to reduce techdebt and improve readability I am removing this module.

Resolves #179

RemoveCSS

Page looks the same after removal

### CODE REVIEW

**Review by brinkbrink — APPROVED** [review]
This makes sense and is working as expected. The removed module is not affecting the display of this page. Thanks! 

p.s. - I changed the "Partial Resolves https://github.com/SeattleColleges/nsc-events-nextjs/issues/177" to "Relates to #179" because GitHub only sees "Resolves" and that will trigger the issue to close if this PR is merged. Relates will connect this PR to the relevant issue. 

I also [converted this task on your user story's task list to an issue](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#converting-tasks-into-issues). Ain't that fancy? That's where the 17*9* is coming from. I didn't fill in the description except to relate it to your user story.

**Review by taylorpapke — COMMENTED** [review]
I'm getting the following error:
Screenshot 2024-02-12 at 3 10 26 PM
What package do I need to install to get this to compile?

**Comment by Exochos** [comment]
> I'm getting the following error: Screenshot 2024-02-12 at 3 10 26 PM What package do I need to install to get this to compile?

I didn't change the packages, I'm unsure of why that's happening

**Comment by brinkbrink** [comment]
Hi @taylorpapke you need [material-next](https://www.npmjs.com/package/@mui/material-next):

`npm i @mui/material-next`

**Review by taylorpapke — APPROVED** [review]
Ok, I got it to work. I just had to reinstall npm for some reason. Sign up page looks exactly like your screenshot.

**Pull request merged**
