### PR TITLE
nsc-events-nextjs-253-route-user-to-homepage-on-sign-in

### LINKED ISSUE #253: USER STORY: Sign in page
As a user, I will want to be routed to the home page upon successfully signing in.

Tasks:
- [x] Signing in as a user should route to the home page and not to the placeholder profile page.

### PR DESCRIPTION
**Pull request by cshimm**
Resolves #253 

Description:
- Users (non creators & admins) will be routed to the homepage upon successfully signing in.

### CODE REVIEW

**Review by nwm516 — APPROVED** [review]
LGTM

**Review by Bejarano03 — COMMENTED** [review]
Your code clearly removes the route to "/profile" and creates a redirect to "/" route.

**Review by Bejarano03 — APPROVED** [review]

**Review by taylorpapke — APPROVED** [review]
This worked for me. I went ahead and created a new user, signed up and was routed to the home page. I signed out, sign back in as a user and was routed once again to the home page.

@keiffer213 Could you please review this PR and merge it once you're done since it has met the requirement of at least 2 approving reviews?

**Comment by keiffer213** [comment]
I got it to work! Following the procedures that Taylor mentioned, I was able to recreate the task and successfully logged in with the user profile. 

image

**Review by keiffer213 — APPROVED** [review]
Refer to my previous comment

**Pull request merged**
