### PR TITLE
nsc-events-nextjs-6-337-fix-incorrect-date-format-logic

### PR DESCRIPTION
**Pull request by cshimm**
The original mm-dd-yyyy date formatting logic was incorrect and would return the date one day before the input date. I believe this was due to time zone discrepancies.

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks good but the sorting is out of order:
Screenshot 2024-05-10 at 1 11 01 PM
Screenshot 2024-05-10 at 1 12 54 PM

**Comment by cshimm** [comment]
Thanks @taylorpapke, I believe that could be fixed with a separate issue because the date formatting shouldn't affect the order. I'll look into that bug as well.

**Review by heosman — APPROVED** [review]
The dates of the events now reflect the correct dates from the database. Definitely going to have to address the sorting of the events in another issue though.

**Review by bennettsf — APPROVED** [review]
Event input date correctly represented. Looks good

**Pull request merged**
