### PR TITLE
nsc-events-nextjs-fixing-responsive-UI-01

### PR DESCRIPTION
**Pull request by Robel-003**
Resolves user story #413  and issue #414 

This PR fixes the styling of the web application so it shows the hamburger menu when the window is shrunk to a smaller size. It also addresses the UI issue where contents in the screen were being cropped out by making the application responsive to changes in window size

Screenshot 2024-06-04 at 2 00 26 PM

Screenshot 2024-06-04 at 2 00 03 PM

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
It seems to be working on my end:
Screenshot 2024-06-04 at 11 22 51 PM
Screenshot 2024-06-04 at 11 22 18 PM

**Review by heosman — COMMENTED** [review]
@Robel-003 The nav bar looks great, it's visible for smaller screens and I'm able to exit the nav bar by clicking outside of it.

Would it be possible for the events to still be displayed in long tiles on bigger screens (like it is on main currently), and decrease in width when displayed on smaller screens, rather than collapse to be side by side? I think that on smaller screens it would be great if the first event (with the photo) was displayed in the center with the rest of the events under. That way the event tiles wouldn't need to be so squished.
This is what the home page looks like on my screen normally:
image

Here is a visual of what I am suggesting:
image

**Comment by kaimanasse15** [comment]
image
Hi @Robel-003, the code looks good but I am wondering why didn't I see the update for the nav bar?

**Comment by brinkbrink** [comment]
@heosman to speed this up for Monday do you want us to merge this to main and then you can apply your changes?

Or if you're around today @Robel-003 could you implement @heosman's idea and then let me know so I can review it and be at least one of the approvals for it? Just think this would be great to include in the demo tomorrow!

**Review by brinkbrink — CHANGES_REQUESTED** [review]
@heosman to speed this up for Monday do you want us to merge this to main and then you can apply your changes?

Or if you're around today @Robel-003 could you implement @heosman's idea and then let me know so I can review it and be the other approving review for this? Just think this would be great to include in the demo tomorrow!

**Comment by heosman** [comment]
> @heosman to speed this up for Monday do you want us to merge this to main and then you can apply your changes?
> 
> Or if you're around today @Robel-003 could you implement @heosman's idea and then let me know so I can review it and be the other approving review for this? Just think this would be great to include in the demo tomorrow!

@brinkbrink It'd be great if the changes to the hamburger nav bar in this PR could be merged but I'm not sure about the other changes as of right now, because it would change the appearance of the pages drastically. Of course if @Robel-003 has already been working on the changes I suggested, and would be able to have it ready to be merged before tomorrow, then it's not a problem.

**Review by heosman — APPROVED** [review]

**Pull request merged**
