### PR TITLE
nsc-events-nextjs _ 4 _ 243 _ change-password-page

### LINKED ISSUE #243: Change Password Page: Create Change Password Page
As a developer, I want to create a Change Password page with a proper UI that includes:
- "New Password" and "Confirm New Password" text field.
-  Change password button
- Functionality integrated with back-end (nests)

### PR DESCRIPTION
**Pull request by TuongPhamM**
resolves #243 
To be able to run this, make sure your back-end supports /change-password endpoints. And during development I removed ENV. URL

https://github.com/SeattleColleges/nsc-events-nextjs/assets/77989401/e88b8afa-186b-4fb0-af3d-705db1281fb3

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Tested this with the backend running and it's working as expected. Very nice UI! I was able to change password and was rerouted to where I could successfully sign in. A toast message was also displayed. Like the PR for the backend, should we be concerned about the package-lock.json getting merged in? If we were to just delete that file from this PR, could we avoid creating a whole new PR?
Screenshot 2024-03-13 at 12 00 30 AM

**Comment by TuongPhamM** [comment]
> Tested this with the backend running and it's working as expected. Very nice UI! I was able to change password and was rerouted to where I could successfully sign in. A toast message was also displayed. Like the PR for the backend, should we be concerned about the package-lock.json getting merged in? If we were to just delete that file from this PR, could we avoid creating a whole new PR? Screenshot 2024-03-13 at 12 00 30 AM

I will double check if it's necessary to merge package-lock.json. If not I will just remove that file off the commit.

**Comment by TuongPhamM** [comment]
The page works without any package-lock.json changes, please review the commit.

**Review by heosman — APPROVED** [review]
With both PRs on the frontend and the backend running, I was able to change the password of my account.

**Pull request merged**
