### PR TITLE
nsc-events-nextjs_9_522_pronoun_field_error

### PR DESCRIPTION
**Pull request by MuhammadNSC**
I fix the "no error showing" when the the field is left empty.
Before Pronoun Validation:
Screenshot 2024-07-11 at 6 54 26 PM
After Pronoun  Validation:
Screenshot 2024-07-11 at 6 08 59 PM

### CODE REVIEW

**Review by heosman — APPROVED** [review]
LGTM! Don't forget to resolve the branch conflicts.

image

**Review by intisarosman1 — COMMENTED** [review]
The error occurs when the user attempts to sign up with an empty pronoun field but this is fixed when they are entered. I did notice that I cannot successfully sign up on this PR (I can on main branch) so it would be best if any conflicts are resolved.
Screenshot 2024-07-12 205737
Screenshot 2024-07-12 211117

**Review by alasali1 — APPROVED** [review]
image
I am able to see the specified error message under the text field as shown, and able to sign up when adding a pronoun.

**Review by heosman — CHANGES_REQUESTED** [review]
I just checked your PR again and it seems the changes you made previously are no longer working. The pronouns field does not show an error when left empty anymore.
image

By the way, is there a reason why there a lot of other pages and components changed in your PR that are not relevant to your issue? The NSC_EVENTS_PUBLIC_API_URL is commented out, which would cause issues, so it will need to be uncommented, and the branch conflicts will need to be addressed, before this PR can be merged.

**Comment by bcko** [comment]
@MuhammadNSC Can you please address the issues from the change request and also resolve conflicts? Thanks

**Review by Asfand00 — COMMENTED** [review]
hey @MuhammadNSC, I also tried testing your branch and ran into the same issue with the pronoun field error not showing up initially:
pronoun-fields

Afterwards the branch started having issues with the pages running properly so I restarted the process, and the results are below:

for some reason the branch isn't working properly on my end this is what I get for the homepage:
events-bad-branch

I'm also getting a bunch of fetch errors when doing things like signing in or when loading events:
error-failed-fetch

not sure what happened maybe its only on my end, but I tested a different branch and it works fine:
events-regular-branch

i also noticed the startup is different too when typing `npm run dev`, not sure if that has anything to do with the errors:
startup-1

Hope some of this helps.

**Comment by bcko** [comment]
Closing this PR. @MuhammadNSC please reopen address issues and fix this

**Pull request closed without merging**
