### PR TITLE
nsc-events-nextjs-10-548-home-page-filter-events-by-tag

### LINKED ISSUE #548: Home Page: Filter events by tag
To implement event filtering by tags on the home page, the following tasks will need to be carried out:

- [ ] Add Tag Selector UI on the home page.
- [ ] Implement logic to filter events based on selected tags.
- [ ] I will create a separate file to store and export the tags array such that it can be reused throughout the project. This will minimize code repetition.

### PR DESCRIPTION
**Pull request by cshimm**
Resolves #548 

Implements filtering the events list on the home page by tags using the TagSelector component. Only events with all of the tags selected will be returned. 
I also moved the list of tags to a separate file `tags.ts` in the `/utility` directory to to be exported and reduce duplicated code. 

Note: Test with the local API as these changes depend on a commit recently merged to the nsc-events-nestjs main branch.

https://github.com/user-attachments/assets/fe971dec-571c-4b51-ba64-dac95c40b3c7

### CODE REVIEW

**Review by bcko — APPROVED** [review]
Great job. Let's get this merged

**Review by intisarosman1 — APPROVED** [review]
I am able to filter with tags on the Home page. Looks good!
image

**Review by heosman — APPROVED** [review]
Clicking the tags effectively filters the events. I'm thinking it would be great for there to be a "Filter by tag" toggle button, rather than just having all of the tags visible by default.

image

**Review by alasali1 — APPROVED** [review]
Looks good to me

**Pull request merged**
