### PR TITLE
nsc-events-nextjs-7-404-unit-test-sign-up-page

### LINKED ISSUE #404: Unit Test: Sign up Page
- [x] Unit test creation to test that the sign-up page functions as expected

### PR DESCRIPTION
**Pull request by MaddasaHatter**
Resolves #404 
- [x] This unit test makes sure that the sign-up page works appropriately as well as the included links and routes.
Screenshot 2024-06-04 224656

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Works on my end:
Screenshot 2024-06-04 at 11 40 23 PM

**Comment by MuhammadNSC** [comment]
All tests passed, i'm curious as to why i'm having 4 tests passed on my end 
Screenshot 2024-06-05 at 10 41 08 PM

**Comment by kaimanasse15** [comment]
The test passed! Thank you for your hardwork!
image

**Comment by keiffer213** [comment]
> All tests passed, i'm curious as to why i'm having 4 tests passed on my end Screenshot 2024-06-05 at 10 41 08 PM

When you run the test, you wanna do an "npm run test test/unit/signup.test.tsx" so that you will just run a specific test, without specifying the test, it will run all of them

**Review by alasali1 — APPROVED** [review]
image
It seems to have run and passed both tests successfully.

**Review by el-riber — APPROVED** [review]
I made the test and it passed 100%!
Screenshot 2024-06-06 at 7 14 37 PM

**Pull request merged**
