### PR TITLE
nsc-events-8-409-implement-material-ui

### LINKED ISSUE #409: Implement Material UI for the remaining pages
Replace Tailwind CSS with Material UI (MUI) for the following pages:

- [x] Home page
- [x] Admin page
- [x] Creator Page
- [ ] My Events page
- [ ] Archived Events page

### PR DESCRIPTION
**Pull request by cshimm**
Resolves #409
This PR converts the following pages from Tailwind CSS to Material UI:
- Home page
- Admin dashboard
- Creator dashboard
- Archived events
- My events

FIXES (bg-solid)

- [ ] Home Page
- [x] Admin dashboard
- [x] Creator dashboard
- [x] Archived Events
- [x] My Events

### CODE REVIEW

**Comment by miqo1385** [comment]
I got this error message when I run this in my end:
Failed to compile
./components/ThemeToggle.tsx:5:0
Module not found: Can't resolve 'react-icons/fi'
  3 | import React from "react";
  4 | import { useThemeContext } from "../app/theme/providers";
> 5 | import { FiMoon, FiSun } from "react-icons/fi";
  6 | 
  7 | const ThemeToggle = () => {
  8 |   // Get the current theme mode and the function to toggle it

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./components/Navbar.tsx

**Comment by cshimm** [comment]
@miqo1385 You may be missing dependencies on your local machine. Try running `npm i` to install any missing dependencies.

**Review by Ali-7s — APPROVED** [review]
LGTM!
MUI implementation looks good
image

**Review by taylorpapke — APPROVED** [review]
All the pages look good and are rendering properly.
home:
Screenshot 2024-06-07 at 1 07 05 PM
admin:
Screenshot 2024-06-07 at 1 08 52 PM
creator:
Screenshot 2024-06-07 at 1 07 12 PM
my events:
Screenshot 2024-06-07 at 1 07 32 PM
archived events:
Screenshot 2024-06-07 at 1 07 43 PM

**Review by heosman — CHANGES_REQUESTED** [review]
I can see that the Home page, Admin page, Creator page, Archived events page, and My Events page all are using MUI now.

Just some tweaks I would like to suggest for consistency:
1. I noticed that the heading text for these pages are bit large compared to the other pages in the app (ex. Edit User Role page). It'd be great if the heading text could be smaller to match.
2. The background colors for these pages are also not consistent with the rest of the app, which is probably due to being overriden by the styles from the home.module.css file. It should be according to the theme, which you can see applied on the Edit User Role page or the Sign In page.

**Review by heosman — APPROVED** [review]

**Pull request merged**
