### PR TITLE
nsc-events-nextjs_5_273_testing-processing-02

### LINKED ISSUE #273: QA Testing: Implement Testing Suite
Relates to #252

### PR DESCRIPTION
**Pull request by Bejarano03**
resolves #273 

This is a pull request!

Please use the following format for the title:
nsc-events-nextjs _ 5 _ 252 _ feature-252-testing-processing-02

Please fill out this description with the following:
Resolves 252
This pull request adds the Jest dependencies needed to run tests. Shown as follows: 

Screenshot from 2024-04-23 01-30-44

The config files allows Jest to use Typescript and the setup file loads up the necessary libraries.
config file:

Screenshot from 2024-04-23 01-33-24

setup file:

Screenshot from 2024-04-23 01-33-55

1. Please run Npm install
2. To run test please use npm run test or npm run test:watch for live development.

### CODE REVIEW

**Comment by Bejarano03** [comment]
https://github.com/SeattleColleges/nsc-events-nextjs/assets/69337575/7d72a267-2882-45f3-ba6d-a70181bc7067

**Comment by taylorpapke** [comment]
It is interesting that this workflow is failing on test:coverage. It was working on previous workflow runs for other PR's but now says that it is missing a script:
Screenshot 2024-04-23 at 1 02 34 PM

Did you run an npm install on main before creating this branch?

Potential troubleshooting options:
As far as getting this to pass CI, I believe we can install coverage (not sure what this command would be) or comment out line 33 and 34 in the following file:
Screenshot 2024-04-23 at 12 58 25 PM

I also see that the test:coverage script has been removed in package.json. Perhaps adding this line back would resolve this issue but I'm not for certain on that.
nsc-events-nextjs package.json:
Screenshot 2024-04-23 at 1 18 34 PM

I believe we need line 12 as shown here in Belindas-closet-nextjs package.json:
Screenshot 2024-04-23 at 1 16 08 PM

**Comment by MuhammadNSC** [comment]
Ran the unit tests on my end and all tests successfully passed. 
Screenshot 2024-04-24 at 4 02 58 PM

**Comment by tinpham5614** [comment]
The test looks good to me, however I'm concerned about the change of many lines of code.

**Comment by Bejarano03** [comment]
I got it to work finally! It had to do with not having a coverage script, and also the Github Actions yml file had the wrong usage of the "npm run" command. After updating these file, these tests can be used. Please review this PR and let me know if there is anything else needed. Thank you.

**Comment by tinpham5614** [comment]
The test result looks good to me.
image

Do you know why there are too many lines of code changed?
image

**Comment by Bejarano03** [comment]
I believe that there are a lot of lines of code changes, because of the Jest Installation and I also needed to get the branch to current by pulling and merging current changes as well.

**Comment by kaimanasse15** [comment]
The test run fine to me

**Comment by MaddasaHatter** [comment]
Looks good to me my test passed

PR Review #252

**Review by cshimm — APPROVED** [review]
Everything runs great on my end, I was able to run all of the jest commands successfully.

**Review by tinpham5614 — APPROVED** [review]

**Review by taylorpapke — APPROVED** [review]

**Pull request merged**
