### PR TITLE
nsc-events-nextjs_3_208_adjust-event-details-card-size

### PR DESCRIPTION
**Pull request by Ali-7s**
Resolves Issue https://github.com/SeattleColleges/nsc-events-nextjs/issues/208

Related to User Story https://github.com/SeattleColleges/nsc-events-nextjs/issues/206

image

Visual draft from google docs: 
image

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks good and the card is appearing larger on my end:
Screenshot 2024-02-24 at 1 12 58 PM

**Review by Exochos — CHANGES_REQUESTED** [review]
As I was reviewing the recent updates, I noticed the use of non-integer values for dimensions and spacings. While the current values achieve the desired layout, I believe adopting whole numbers could enhance the readability and maintenance of our code.

**Review by heosman — APPROVED** [review]
Looks good!

image

**Review by Exochos — APPROVED** [review]
Ty! Sorry to be a pain!
Looks great 👍

**Pull request merged**
