### PR TITLE
nsc-events-nextjs-6-288-home-page-events-pagination

### LINKED ISSUE #288: Home Page: Implement pagination and display 5 additional events on "Load more events" button clicked
As a user, I would like to be able to view more than just the 5 default events. This should be accomplished by clicking a "Load more events" at the bottom of the home page. When clicked this button should load 5 more events until there are no more additional events to load. Archived and deleted events should now show.

- [x] Add "Load more events" button
- [ ] 5 additional events should be loaded on the home page on button click
- [ ] Do not load archived and deleted events.

### PR DESCRIPTION
**Pull request by cshimm**
### Note: This branch depends on SeattleColleges/nsc-events-nestjs#110. Until it is merged to main, please make sure to checkout branch `bug-110-remove-duplicate-get-handler` in the nsc-events-nestjs repo before testing this feature.

Resolves #288

A "Load more events" button has been added and on click, 5 new events will be loaded until the end of the events list has been reached. When all of the events have been rendered, the Load More Events button will not be rendered anymore.
image

Video demonstrating pagination both logged in and logged out:

https://github.com/SeattleColleges/nsc-events-nextjs/assets/13278479/e7b4f7ff-2cc3-4552-a829-234a81a4a2dc

### CODE REVIEW

**Review by taylorpapke — DISMISSED** [review]
Works for me while logged in and out. It loads up to 5 more events every time I click the button:
Screenshot 2024-04-30 at 2 11 43 AM

**Review by IsaacJrTypes — APPROVED** [review]
Looks good. Making a note that we are using the api directly over the use effect library. Great negation technique lol
CleanShot 2024-04-30 at 11 49 53

**Review by tinpham5614 — APPROVED** [review]
Looks good to me.
It would be great if you could provide some comments for ease of reading and understanding of the logic. For example in line 34.

**Comment by cshimm** [comment]
Thanks @tinpham5614. I changed the variable name to `activeEvents `and added a comment above the filter line for clarity.

**Comment by miqo1385** [comment]
I've been trying to find this branch in nextjs and nests but I can't find it. where is it or this is already merged??

**Comment by Ali-7s** [comment]
Not sure why but I'm met with this error:
image

**Comment by cshimm** [comment]
@Ali-7s Yea I had to re-address this issue so I'm still working on it. Once it's ready I'll take it out of draft mode and open it to review.

**Comment by cshimm** [comment]
Re-opened. Please checkout branch `bug-110-remove-duplicate-get-handler` in the nsc-events-nestjs repository to test.

**Review by nickolasram — CHANGES_REQUESTED** [review]
I’ll “request changes” just so this doesn’t get prematurely merged while we check out the updates

**Review by taylorpapke — APPROVED** [review]
Still works:
Screenshot 2024-05-09 at 12 53 45 PM

**Review by nickolasram — APPROVED** [review]

**Comment by tinpham5614** [comment]
It works as expected.

**Review by tinpham5614 — APPROVED** [review]

**Comment by cshimm** [comment]
@tinpham5614 @nickolasram @heosman Can you guys review this PR in the nestjs repo  [@SeattleColleges/nsc-events-nestjs/#111](https://github.com/SeattleColleges/nsc-events-nestjs/pull/111) ? Since the pagination depends on it, it won't appear to work currently if you're on the main branch in the nestjs repo.

**Pull request merged**
