### PR TITLE
nsc-events-nextjs_7_376_role-authorize-create-event

### LINKED ISSUE #376: Role-based authorization: Create Event page
Tasks:

- [x] Restrict access to Create Event page
- [x] Redirect the user to page with 401 Unauthorized status code when attempting to access these pages

### PR DESCRIPTION
**Pull request by kaimanasse15**
Resolves #376

I am working on the role authorize and not sure if it is working. This is a total new field for me.

### CODE REVIEW

**Review by bennettsf — APPROVED** [review]
Looks like you're on the right track! Just need to implement this for all of the other pages.

**Review by Ali-7s — APPROVED** [review]
LGTM! 
Wasn't able to access the create-event page after signing out.
image

**Review by taylorpapke — APPROVED** [review]
Works for me:
Screenshot 2024-05-26 at 2 03 05 PM

**Review by intisarosman1 — APPROVED** [review]
I'm not able to access the Create Event page as this PR intends.

Screenshot 2024-05-26 224030

**Review by heosman — APPROVED** [review]
Good work, I tested as a user and while not signed in and was restricted from accessing the Create Event page.

image

**Comment by MaddasaHatter** [comment]
Looks good
Screenshot 2024-05-27 163105

**Pull request merged**
