### PR TITLE
nsc_event_8_437_blue-logo-dropdown-with-signet-and-myAccount

### PR DESCRIPTION
**Pull request by miqo1385**
Please fill out this description with the following:
Resolves <issue #437 >

Description :  Change "Profile" button text to "My Account", Add blue vertical NSC logo above nav bar links (should be centered),Widen nav bar and center nav bar links, Clicking outside of nav bar element should close nav bar

https://github.com/SeattleColleges/nsc-events-nextjs/assets/97195623/f1eacb8c-136b-492d-b732-8e4b60f483ba

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Everything works for me. I'm getting the same results as in your screen share.

**Review by Asfand00 — APPROVED** [review]
Looks good on my end as well, getting same results as your video:

one minor thing (just being picky), the nsc logo shifts a bit when signing in and signing out but other than that it looks great, ill approve 
nsc-events
nsc-events2

small window:
nsc-events3

**Review by heosman — DISMISSED** [review]
I got the same results as your video, but I would suggest adding the Sign In link back to the nav bar when not signed in. I also think the hamburger dropdown should stay to the far right on smaller screens, rather than in the center.

**Comment by heosman** [comment]
Resolves #285 and #437

This PR:
- Adds profile icon, which when clicked has "My Account" and "Sign Out" links for admins and creators, and only a "Sign Out" link for normal users
- Adds "Sign In" link back to nav bar when not signed in
image

For hamburger nav menu:
- Adds blue vertical NSC logo above nav bar links
- Widens nav bar and center nav bar links
image

**Review by intisarosman1 — APPROVED** [review]
The dropdown looks like it should, LGTM!

image

**Pull request merged**
