### PR TITLE
nsc-nextjs-02-156-sign_in_function

### LINKED ISSUE #157: Sign In Page: Add sign-in function
As a developer, I want to implement a sign-in feature that allows users to access further activities such as event creation and user management.

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #157 
Related #156 

As a developer, I want to implement a sign-in feature that allows users to access further activities such as event creation and user management.

**Approach:**

1. Replaced the "signIn" method from the "next-auth" library with "fetch" method to handle user login.
2. Retrieved user role by decoding the JWT.
3. Redirect to the user page

**Before testing function:**
1. Ensure you have a user account in the database. If not, you can use Postman to create one.
2. Ensure the frontend and backend are running at the same time. 
**Important: Backend not running -> APIs not called -> function doesn't work.**

Demo:

https://github.com/SeattleColleges/nsc-events-nextjs/assets/72054441/cca86957-4f7e-4620-a874-2c7b863b2da0

### CODE REVIEW

**Review by heosman — COMMENTED** [review]
Strangely, when I sign in (either using an account I already made or with a new account I just signed up with), I get this error:

Screenshot 2024-02-01 210101

**Comment by tinpham5614** [comment]
@heosman Is the NSC backend NestJS running?
On my side, I tested without backend running and received the same error as yours.

**Comment by heosman** [comment]
> @heosman Is the NSC backend NestJS running? The backend and front end should be running at the same time. On my side, I tested without backend running and received the same error as yours.

@tinpham5614 Oh, I see! When I try it with the backend running, I get another error though.

Screenshot 2024-02-01 211035

Screenshot 2024-02-01 211054

**Comment by tinpham5614** [comment]
Make sure the email and password are correct and are in the database.
Looking at the screenshot, I guess it may be a typo.

**Comment by heosman** [comment]
> Make sure the email and password are correct and are in the database. Looking at the screenshot, I guess it may be a typo.

I just noticed that the users aren't being saved to the database when I sign up. Looks like I'll have to figure out why that's happening first.

**Comment by tinpham5614** [comment]
You can use Postman to create one without issues since the backend currently working fine with all endpoints.

**Review by heosman — APPROVED** [review]
Thank you for the tips, it's working for me now. I noticed that the Create Event and Sign out links are no longer in the nav bar, probably because next-auth library was used to make the AuthProfileMenu show. What can we do about this?

**Comment by tinpham5614** [comment]
Yes, we will need to discuss modifying this to match our implementation.

**Review by taylorpapke — APPROVED** [review]
Seems to be working as expected. I first tried to login in with all 3 roles without the backend and was unable. With the backend, I was routed to admin page from admin role, creator page from creator role and profile from user role.

**Comment by NahomAlemu** [comment]
Sorry if I missed this discussion. I was wondering.
- Why do we need to shift from the next-auth to a direct fetch call?
- Does next-auth support what you are trying to accomplish using fetch?

**Comment by tinpham5614** [comment]
> Sorry if I missed this discussion. I was wondering.
> 
> * Why do we need to shift from the next-auth to a direct fetch call?
> * Does next-auth support what you are trying to accomplish using fetch?

As I understand it, we have a backend built with NestJS that has API endpoints that enable communication with mobile applications. The Fetch API endpoints help us to manage the apps smoothly and maintain consistency. If any changes are made to the backend, they will also be reflected in the web and mobile apps.
For example:
In the Belinda app, we need to categorize the products based on their types. To achieve this, we require an API endpoint in the backend which will be called in the frontend using NextJS and mobile (which I don't think next-auth can be applied in mobile). This will provide us with the desired output.

I would like to learn from your perspective. What do you think?

**Pull request merged**
