### PR TITLE
Show events on homepage

### PR DESCRIPTION
**Pull request by Ali-7s**
Satisfies issue #140 
Added an EventGetter component that uses ReactQuery to get events, if there are any. 
To make ReactQuery work, I also added a ReactQueryProvider component. Used MUI to stylize and format event cards.

image

### CODE REVIEW

**Review by tinpham5614 — CHANGES_REQUESTED** [review]
Please check the "Details" for errors.

**Review by bcko — APPROVED** [review]
@Ali-7s great work on using React Query in your pull request. Before we can merge, please address the existing linting errors. I am approving this pull request under the condition that these linting errors will be fixed.

**Comment by Ali-7s** [comment]
> Please check the "Details" for errors.

I've fixed the issues

**Comment by bcko** [comment]
Great job. We will merge your pull request. Keep up the great work

**Pull request merged**
