### PR TITLE
nsc-events-nextjs-8-393_add_user_details_to_profile_page

### LINKED ISSUE #393: Profile Page: Add user detail card.
- [ ] Replace the placeholder text on the profile page with a card that displays the current user's details (name, email, pronouns). 
- [ ] Add a "Change password" button that routes the user to the Change Password page

### PR DESCRIPTION
**Pull request by cshimm**
resolves #393 

This PR adds a user card to display the current user on the Profile page as well as a button that routes to the Change Password page. 

Profile page signed in:
image

Profile page signed out:
image

To Test:
- manually navigate to '/profile' in the browser. There is no 'profile' link yet. 
- navigate to '/profile' while signed in and signed out.

I also added a new util file called userUtils and moved a function to get the current user's Id since it is needed in multiple files.

### CODE REVIEW

**Comment by miqo1385** [comment]
when I tried to sign in from your branch, it doesn't do anything, I mean it doesn't redirect to any page. I don't know why.

**Review by nwm516 — APPROVED** [review]
Very nice. I had similar results within my own environment, as well. LGTM.

Profile Card

**Review by TuongPhamM — COMMENTED** [review]
I like the initial profile look and it works on my end. However, keep in mind that we have Nest server running on Cloud and I find it easier fetching user id from there so reviewers or anyone who runs this code won't have to host back-end locally. You can replace fetching URL with `const URL = process.env.NSC_EVENTS_PUBLIC_API_URL || "http://localhost:3000/api";`, they're also used in auth/sign-in/page.tsx if you want to see how it works. But overall, LGTM. 
Screenshot 2024-06-03 144125

**Review by heosman — APPROVED** [review]
Looks good and Change Password link routes to Change Password page.

image

**Review by taylorpapke — APPROVED** [review]
Works for me:
Screenshot 2024-06-04 at 9 59 22 PM

**Pull request merged**
