### PR TITLE
nsc-events-nextjs-5-247-attend-event-functionality

### PR DESCRIPTION
**Pull request by Ali-7s**
* Added AttendDialog 
* Implemented attend event functionality 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/22021615/8c0f2904-fb19-4a46-82f8-11237d1f325d

image

### CODE REVIEW

**Review by intisarosman1 — COMMENTED** [review]
The attendance count goes up when I am logged in and submit my name for attendance through the Attend button. 
I noticed that the button still functions while logged out though (attendance count does not go up). Maybe the button should prompt the user to log in if they try to click the button while logged out?

**Review by taylorpapke — APPROVED** [review]
I was able to attend with and without adding my name for the user, creator and admin. The attendanceCount increments correctly and the user's name is added to the array of attendees when I check the box:
Screenshot 2024-04-30 at 1 16 24 AM
Screenshot 2024-04-30 at 1 26 44 AM

**Review by tinpham5614 — APPROVED** [review]
Looks good!

**Comment by MaddasaHatter** [comment]
I was able to pull and run the branch before it got deleted and merged with no issues and the attendance link worked as expected, good job on fixing the issues with this request.

**Pull request merged**
