### PR TITLE
nsc-events-nextjs-8-420-update-nsc-logo-on-auth

### PR DESCRIPTION
**Pull request by Ali-7s**
Satisfies #420 
* Added white_logo.png
* Implemented logo change on sign in

https://github.com/SeattleColleges/nsc-events-nextjs/assets/22021615/0f742a31-5f8e-414d-bd02-13d89dc5a19e

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
I'm seeing the white logo on my end:
Screenshot 2024-06-04 at 11 33 35 PM

**Review by MaddasaHatter — APPROVED** [review]
LGTM I can see the white logo
Screenshot 2024-06-05 003055

**Comment by heosman** [comment]
@Ali-7s I'm sorry, It seems I made a mistake with this user story. What I meant was that the NSC logo in the corner of the nav bar should use the white NSC Logo (no matter if signed in or not), but the NSC logo in the Welcome Container should use the blue NSC logo, which I just added to the Media Kit.

**Comment by Ali-7s** [comment]
> @Ali-7s I'm sorry, It seems I made a mistake with this user story. What I meant was that the NSC logo in the corner of the nav bar should use the white NSC Logo (no matter if signed in or not), but the NSC logo in the Welcome Container should use the blue NSC logo, which I just added to the Media Kit.

No worries and is this the blue one meant for the Welcome Container? The only blue logo I see in the media kit is the larger one with the school name on it
image

**Comment by heosman** [comment]
> > @Ali-7s I'm sorry, It seems I made a mistake with this user story. What I meant was that the NSC logo in the corner of the nav bar should use the white NSC Logo (no matter if signed in or not), but the NSC logo in the Welcome Container should use the blue NSC logo, which I just added to the Media Kit.
> 
> No worries and is this the blue one meant for the Welcome Container? The only blue logo I see in the media kit is the larger one with the school name on it image

That logo currently in the Welcome Container (in your screenshot) should be replaced with the blue NSC logo from the [media kit](https://www.notion.so/Media-Kit-3db9f96a49f646d3b3dd6645f87745dc). 
This is the one: 
image

**Comment by cshimm** [comment]
This is what I see when logged out on the home page.

image

The navbar logo is white for every other page. Is that what we're going for?

**Review by heosman — APPROVED** [review]
LGTM! @cshimm Yes, that's how it should be looking.

**Comment by nwm516** [comment]
Late to the party but LGTM.

NSC Logo on Auth

**Pull request merged**
