### PR TITLE
nsc-events-nextjs_10_555_eventpagedetailsdocfield

### PR DESCRIPTION
**Pull request by RMaffei**
Updated moreDetails and activityDatabase.ts to reflect these changes

Resolves issue 555

Add new document field to 'More Details' dialog, make changes in component 'ViewMoreDetailsDialog' to include this new field as well as update in activityDatabase.

Because I have added this functionality, I needed to update the ‘ActivityDatabase’ to include a type definition for ‘document’. I did this within the activityDatabase.ts file.

### CODE REVIEW

**Comment by bcko** [comment]
@RMaffei Please convert this pull request from draft to Ready for review when you are ready

**Comment by Alzavio** [comment]
Is this ready for review?

**Comment by Alzavio** [comment]
I believe this is working
image

**Comment by ParysUnangst** [comment]
Circling back in the event that this PR still needs review. I agree with Alzavio that we should leave out the undefined portion if there is nothing there. It can always be added in at a later date if needed.

**Comment by ken-ni** [comment]
I created an event with a document included and it still showed the document field as "undefined". It also shows the document field twice for some reason.
undefined

Although, I'm not sure if documents are actually being stored upon event creation since the "Event Document" field does not show when editing events.

**Comment by BradleyCharles** [comment]
Student is not participating this term. I am closing this so it can be completed by someone else

**Pull request closed without merging**
