### PR TITLE
nsc-events-nextjs_3_205_refactor-create-event-page

### LINKED ISSUE #205: USER STORY: Improve User Interface for Event Creation
As a developer, I want to enhance the "Create Event" Page Interface. The page currently has a few UI issues that affect the user experience, including conflicting placeholder text and input field labels, and an incorrect button color for the "Create Event" button. I also want to refactor the TagSelector component to material Ui
Issues:

- [x] Resolve Input Field Label and Placeholder Text Conflicts
- [x] Optimize codebase, use better MUI components
- [x] Update Create Event Button Color
- [x] Refactor TagSelector component

### PR DESCRIPTION
**Pull request by NahomAlemu**
resolves #205 #215 
 
Changes:
- Resolve Input Field Label and Placeholder Text Conflicts
- Update Create Event Button Color
- Refactor TagSelector component
- In addition to the initial user story requirement I have made a significant change to the codebase optimization by using proper MUI components and moving the custom theme to the themes file, refactoring the TagSelector, and removing redundant styling implementations. 

Suggestions:
- This page still needs some improvement - the time and date picker is implemented using react libraries, perhaps we can use MUI for consistency.
- The sample events in the input fields are created using auto-filling text. I think using a placeholder would be generally more user-friendly for creating new events to guide users without the risk of unintentional submission of the default data. 

Screenshot 2024-02-27 at 8 52 29 PM
Screenshot 2024-02-27 at 8 58 20 PM

### CODE REVIEW

**Review by heosman — CHANGES_REQUESTED** [review]
Good job on fixing the input text field conflicts. I agree with you on using placeholder text instead of autofill to make sure the user doesn't submit the default text.

I think the input text fields should look similar to the inputfields on the Sign up and Sign In pages, with a white background and black text. It is a bit dificult to read at the moment because of the low contrast. The text field labels should also be black, similar to Event Date and Event Tags.

**Comment by brinkbrink** [comment]
Thanks for bringing this up @heosman. I want to conduct an accessibility audit next sprint. Here's an interesting [blog post](https://tangledweb.xyz/please-stop-using-grey-text-3d3e71acfca8) about contrast and readability. Feel free to make initial changes in this PR but we can also fix it next sprint @NahomAlemu.

**Review by brinkbrink — APPROVED** [review]
Everything else is working as expected. A lot of great changes made here.

**Comment by NahomAlemu** [comment]
> I think the input text fields should look similar to the inputfields on the Sign up and Sign In pages, with a white background and black text. It is a bit dificult to read at the moment because of the low contrast. The text field labels should also be black, similar to Event Date and Event Tags.

That makes sense. I wanted to change it but I thought this was the client's requirement. I think if we make the background white instead of gray, it will create a better contrast and will solve most of the readability issues. Let me know if you want me to do that along with your suggestions.

**Comment by NahomAlemu** [comment]
> Here's an interesting [blog post](https://tangledweb.xyz/please-stop-using-grey-text-3d3e71acfca8) about contrast and readability. Feel free to make initial changes in this PR but we can also fix it next sprint @NahomAlemu.

Couldn't read the whole article, needs an account 😞

**Comment by brinkbrink** [comment]
For those without a Medium subscription a lot of the article is based on these comments [here](https://github.com/w3c/wcag/issues/695), which are public.

**Comment by heosman** [comment]
> > I think the input text fields should look similar to the inputfields on the Sign up and Sign In pages, with a white background and black text. It is a bit dificult to read at the moment because of the low contrast. The text field labels should also be black, similar to Event Date and Event Tags.
> 
> That makes sense. I wanted to change it but I thought this was the client's requirement. I think if we make the background white instead of gray, it will create a better contrast and will solve most of the readability issues. Let me know if you want me to do that along with your suggestions.

No worries, because the client requested the input text fields to be white with black text on some of the other pages, I think it would be good to apply this to all of the pages for consistency and readability. You can go ahead and change it in this PR.

**Comment by NahomAlemu** [comment]
> No worries, because the client requested the input text fields to be white with black text on some of the other pages, I think it would be good to apply this to all of the pages for consistency and readability. You can go ahead and change it in this PR.

I can make the changes in this PR. Here is the difference between making the background theme white and only the text field white. It seems a bit off to me for this page to change just the input field text. But that is just my opinion. Also, other pages will remain readable with a white background of the theme. For example; sign up page.

Screenshot 2024-02-27 at 7 49 33 PM

Screenshot 2024-02-27 at 7 56 16 PM

Screenshot 2024-02-27 at 7 59 06 PM

**Comment by heosman** [comment]
> > No worries, because the client requested the input text fields to be white with black text on some of the other pages, I think it would be good to apply this to all of the pages for consistency and readability. You can go ahead and change it in this PR.
> 
> I can make the changes in this PR. Here is the difference between making the background theme white and only the text field white. It seems a bit off to me for this page to change just the input field text. But that is just my opinion. Also, other pages will remain readable with a white background of the theme. For example; sign up page.
> 
> Screenshot 2024-02-27 at 7 49 33 PM Screenshot 2024-02-27 at 8 06 24 PM Screenshot 2024-02-27 at 7 59 06 PM

I agree that it looks better when the background color of the page is changed instead of the background of the input text. Perhaps we should do this instead?

**Comment by NahomAlemu** [comment]
> I agree that it looks better when the background color of the page is changed, instead of the background of the input text field. Perhaps we should do this instead? We need to make sure that the Event Tags, Event Date, and the other types of fields are still readable though.

I think so. I just made the changes. Please take a look. "Select Date" is gray because the Datepicker component from "react-datepicker" does not support inline styling for its placeholder. This will be black when we refactor the Datepicker to MUI.

**Review by heosman — APPROVED** [review]

**Pull request merged**
