### PR TITLE
nsc-events-nextjs_6_342_unit-test-create-event-page

### PR DESCRIPTION
**Pull request by kaimanasse15**
I wrote the test and base on the page but I don't know why it is still errors at the render part

### CODE REVIEW

**Review by taylorpapke — CHANGES_REQUESTED** [review]
I'm not sure about this. There's some errors here but I don't know how you would resolve them:
Screenshot 2024-05-09 at 12 58 07 PM

Maybe try an easier test?

**Comment by brinkbrink** [comment]
@kaimanasse15 I see the latest commits are two weeks ago and tests are still failing. Did you want to close this PR without merging or are you still working on this?

**Comment by MaddasaHatter** [comment]
I can see the PR is still not passing the checks I am not sure if this is still being worked or now but it needs some work to be able to merge.

**Comment by taylorpapke** [comment]
Closing due to inactivity. Reopen if needed.

**Pull request closed without merging**
