### PR TITLE
nsc-events-9-bug-518-invalid-start-and-end-times

### LINKED ISSUE #518: BUG: Fix errors for Start Time and End Time fields in Edit Event dialog
1. When editing an event, start time and end time fields have a red outline as if there is an error, when there is none. It does not affect the changes being saved, but it should be fixed to avoid confusion. 
image

2. In addition, these two fields should display the time that was set previously for the event, rather than "hh:mm aa" like it does currently. This is what it should look like:
image

### PR DESCRIPTION
**Pull request by cshimm**
resolves #518 

This PR fixes the start and end time picker fields error. Events whose start and end times are formatted with a space between the time value and the time of day are not parsed properly and so the times must be formatted as such: "XX:XXAM" or "XX:XXPM"
"10:00 AM" -> "10:00AM"

The function I used to remove the whitespace uses a common regex pattern for removing whitespace.

https://github.com/SeattleColleges/nsc-events-nextjs/assets/13278479/172bb87d-585a-4a7e-8482-bfea84779fe0

### CODE REVIEW

**Review by heosman — APPROVED** [review]
Looks great! The Start Time and End Time fields no longer display as errors in the Edit Event dialog and show the correct dates properly. 

image

It's probably not related to this PR, but I noticed that when I change the date or time fields, I am unable to save my changes. I'll create another bug issue for this.

**Comment by cshimm** [comment]
@heosman I can take a look at that and see if its related to this one and if not I can pick up the other one

**Review by intisarosman1 — APPROVED** [review]
The date times are now correct and match that of the event without the format error.
Screenshot 2024-07-07 212542

**Comment by heosman** [comment]
> @heosman I can take a look at that and see if its related to this one and if not I can pick up the other one

@cshimm I checked on the main branch and it seems to be an issue there too, so don't think it's this PR. I've created the [issue](https://github.com/SeattleColleges/nsc-events-nextjs/issues/525) so feel free to assign yourself.

**Pull request merged**
