### PR TITLE
nsc-events-nextJS_5_47_homepage-addition-UI-update

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves: #47

This PR will add the homepage to the current web and also update the UI.

**Home Page**
homepage

**Login Page**
homepage

**SignUp Page**
homepage

**Forgot Password Page**
homepage

**Profile Page**
homepage

### CODE REVIEW

**Review by Seiyaroo — APPROVED** [review]
Based on what I saw from the presentation yesterday, it LGTM!

**Review by taylorpapke — APPROVED** [review]
Looks Awesome!

**Review by theGaryLarson — COMMENTED** [review]
@tinpham5614 LGTM. I wasn't able to recreate your errors you are getting in the screenshots though. Interested in hearing you have more info about them.

Awesome work getting it all connected.

### Todo (for the record):
- [x] check user role before assigning access to Create Page
- [x] Fixing profile page
- [x] Add route to admin page in navbar. 
- [ ] conditionally render "Create Event" or "Admin Page" on the NavBar

Awesome job Tin! Thank you!!

**Comment by tinpham5614** [comment]
@theGaryLarson the errors that I fixed were in the CSS file that was checked by the plug-in (I forgot the name). For the errors in the screenshots, I'm not sure but I will research to solve them.

**Pull request merged**
