### PR TITLE
nsc-events-nextjs-01-163-Add EventDate DatePicker, eventStartTime Picker and eventEndTime Picker

### LINKED ISSUE #163: Create Event Page: Add EventDate DatePicker, eventStartTime Picker and eventEndTime Picker
relates to #144

### PR DESCRIPTION
**Pull request by Robel-003**
resolves #163

This pull request adds on to the create event page adding a date picker for the event date field and a time picker for the start and end time fields. It also handles the logic for accurate date and time selection so all dates will be for future selection, and all end times would be after the start times. I’ve also added some error handling for input fields.

Screenshot 2024-02-01 at 8 45 28 AM

Screenshot 2024-02-01 at 8 45 37 AM

Screenshot 2024-02-01 at 8 46 10 AM

### CODE REVIEW

**Review by heosman — COMMENTED** [review]
@Robel-003 I'm getting this error on my end when I try to access the Create Event page:

image

**Comment by Robel-003** [comment]
> @Robel-003 I'm getting this error on my end when I try to access the Create Event page:
> 
> image

@heosman I imported the datepicker package into this project which might be a new package you'd have to install when running this project. Did you "npm install" in the command line after hopping into the branch?

**Comment by tinpham5614** [comment]
It works after running "npm install". 
However, there is still an error that I believe is caused by spacing issues. You can use "Prettier," which is one of the extensions that I use to format my code.

**Comment by heosman** [comment]
@Robel-003 The datepicker, start-time picker and end-time picker fields are working great. A suggestion would be to make the selected date in the date field black, so it is visible, and change the date format to mm/dd/yyyy.

**Review by heosman — APPROVED** [review]

**Comment by Robel-003** [comment]
My apologies for the delay in fixing the code factor issues but I was able to fix those issues creating a hook for the date/time selection and clean up the useEventForm hook. I also leveraged the InputField component to switch the css to material UI

**Comment by heosman** [comment]
@Robel-003 I just looked over the new changes and one of the things I noticed is that because the background and input field borders are both black, I can only view the input fields if I press them. I had to temporarily change the color of the background on the globals.css on my end so I could test the fields. 

Screenshot 2024-02-06 201521


After I click on an input field:
Screenshot 2024-02-06 201640

Also, when I press the date picker, I can see the labels of the other input fields through the calendar.
Screenshot 2024-02-06 202436

Other than that, great job on the image picker.

**Review by taylorpapke — APPROVED** [review]
I couldn't figure out which package to install for the time picker but everything else seems to be working. The text for the event date field is still not visible at this time.

**Pull request merged**
