### PR TITLE
nsc-events-nextjs-3-226-navbar-auth-updates

### LINKED ISSUE #226: NavBar: Auth Updates
relates to #220 

This issue is for several improvements to the authentication flow for the navigation bar.

### PR DESCRIPTION
**Pull request by NahomAlemu**
Resolves #226

This PR introduces several refinements to the authentication flow as we shifted from next-auth and the drawer component streamlines the authentication state management.

### Changes
- Added 'useAuth` hook.
- Updated `DrawerComp` to a functional component to leverage hooks for state management.
- Implemented a conditional rendering strategy in `DrawerComp` to show a "Sign In" button for unauthenticated users, facilitating easier navigation to the sign-in page.

https://github.com/SeattleColleges/nsc-events-nextjs/assets/55855783/fdc44c8e-cfe8-49ad-9e4b-3aedbed5615b

### CODE REVIEW

**Review by heosman — CHANGES_REQUESTED** [review]
Sorry, I don't think I was clear enough at the time, so here are some more clear instructions for the routing in the nav bar.
- NSC logo and Home links should both route to the home page
- Instead of a Create Event link, there should be a link called "Dashboard" (for now), and where it routes to depends on the role of the user. It should route to the Admin page for admin users, and to the Creator page for creator users.

**Comment by NahomAlemu** [comment]
> * NSC logo and Home links should both route to the home page
> * Instead of a Create Event link, there should be a link called "Dashboard" (for now), and where it routes to depends on the role of the user. It should route to the Admin page for admin users, and to the Creator page for creator users.

No problem. I was also more focused on getting the state management working.
Just to make sure, should be like this?
Screenshot 2024-02-29 at 8 42 31 PM (2)
Screenshot 2024-02-29 at 8 42 39 PM (2)

**Comment by heosman** [comment]
> > * NSC logo and Home links should both route to the home page
> > * Instead of a Create Event link, there should be a link called "Dashboard" (for now), and where it routes to depends on the role of the user. It should route to the Admin page for admin users, and to the Creator page for creator users.
> 
> No problem. I was also more focused on getting the state management working. Just to make sure, should be like this? Screenshot 2024-02-29 at 8 42 31 PM (2) Screenshot 2024-02-29 at 8 42 39 PM (2)

Yes, that looks great.

**Review by heosman — APPROVED** [review]
I signed in as an admin, a creator, and a user, and was routed to the correct page when I clicked the dashboard link for the admin and the creator accounts. The dashboard link in the nav bar was not visible when I signed in as a user. The sign out link is also working, good job!

**Pull request merged**
