### PR TITLE
Added filter events by tags feature and resolved image path issues

### LINKED ISSUE #564: Home Page Add "Filter by tags" toggle button that toggles visibility of event tags
This is an issue!
Task 1: To add 'filter by tags' button for the events to be filtered out.

**Issues NOT related to the main issue**

Task 2:  to fix image reference issue caused by import in next.js -- to use direct reference for the images from the public/images path.

**Files to be affected by the updates**:
Image

### PR DESCRIPTION
**Pull request by gitbiruk2010**
This is a pull request!

https://github.com/SeattleColleges/nsc-events-nextjs _ sprint 13 _ #564  _ Home Page Add "Filter by tags" toggle button that toggles visibility of event tags
image
Resolves #564 

**Images loading properly on both sign-in/up, and forgot-password pages.**

image
image

Local test:
https://github.com/user-attachments/assets/ac9c91e9-c67d-4c53-8573-64f877a542cd

### CODE REVIEW

**Review by ken-ni — APPROVED** [review]
These changes look good, the "filter by tags" feature works well and it seems like the images are loading properly on the pages you referenced:

https://github.com/user-attachments/assets/400a7398-379d-4814-a190-14bf44d702f3

Also, I'm not sure if it's applicable here, but it was mentioned in class that using the caret notation in dependencies (package.json) can cause issues. Please correct me if I'm wrong.

**Review by Asfand00 — CHANGES_REQUESTED** [review]
Looks good on my end as well, I'm seeing the same changes as your video in mine:

https://github.com/user-attachments/assets/cfe81c40-a7c8-4ab9-8c49-787964efe25a

@keiffer213 you mentioned about the karat thing, I believe it does apply here still and to be safe as @bcko mentioned during the meeting. we should get rid of the karats, so we don't introduce new minor issues and enforce stability in our projects so ill hold off on approving until the karats are removed @gitbiruk2010 

dependencies-karat
  

It looks like next and next/auth were updated which as well is a different version from main branch currently. Don't know if that was safe to do but something to notice. Definitely would like others' opinions on this.

**Comment by gitbiruk2010** [comment]
@Asfand00 totally forgot the conversation we had to remove carets to avoid issues with versions. Carets are kicked out!
**next** & **next-auth**  updates: you're right, it could infact cause some breaking changes mostly on routing, server side rendering, or api handling, which sounds not good. Just to be on the safe side, i have rolled those versions back to the prev one. Thanks for the insight.

**Review by BradleyCharles — APPROVED** [review]
Changes look great!
The changes that @Asfand00 recommended concerning the carets and the _next_ and _next/auth_ updates seem to be adjusted and working as well.
Good Job!


Screenshot 2024-10-21 110758
Screenshot 2024-10-21 110804

**Review by Asfand00 — APPROVED** [review]
Awesome, I don't see any carets, and the next and next/auth were corrected as well, nice work @gitbiruk2010. 
nsc-events-nextjs-dependecy-carets

The tag filter still works as intended as well

**Comment by ParysUnangst** [comment]
Great feature update! This will make it much easier!
Screenshot (1)
Screenshot (2)

**Pull request merged**
