### PR TITLE
nsc-events-nextjs-293-arrow-icon-functionality-01

### LINKED ISSUE #293: USER STORY: Event Detail Page
As a developer, I will want to change the date format of events and also want to incorporate arrow icons to navigate through the listed events.

Issues:
- [x] #294 
- [x] #295

### PR DESCRIPTION
**Pull request by Robel-003**
Resolves #293 

This pr adds functionality to the arrows in the event-detail page. When the right/left arrow is clicked, the event being displayed switches to the next one. If there are no more events, the right/left arrow will disappear. This allows users to cycle through events within the event-detail page without having to go the events page. Once a user reaches the end of their list of events, the right/left arrow disappear indicating reaching the end of the list.

### CODE REVIEW

**Comment by brinkbrink** [comment]
If you have a second today or tomorrow could you resolve these conflicts? I went through and started but there are a few that I think would be easier for you to make sense of. Thanks, @Robel-003 !

**Comment by MaddasaHatter** [comment]
Nothing happens when I click, am I in the right place?

https://github.com/SeattleColleges/nsc-events-nextjs/assets/52189566/14541a21-1630-418d-b627-ed4165643e88

**Review by larsswenson — CHANGES_REQUESTED** [review]
I'm having the same issue with arrow functionality mentioned here.

**Comment by Robel-003** [comment]
*fixed* just realized I had some parts commented out. I'm currently having trouble loading the next/previous event due to an undefined _id for the next/previous event, but it's calling the correct _id for an event. As a temporarily fix, I logged the event _id that it's calling the console and kept the page in the same event or in a "Is Loading" page.
I'm able to see all the events in the list of events for a given user in the console but I'm having trouble loading that event to the page

**Review by TuongPhamM — CHANGES_REQUESTED** [review]
I can see the arrows but when I click on it, the URL added "..page.tsx?..."and the page does nothing until I click refresh (the URL did not work either). From the attached video, I think that part jammed the function. 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/77989401/5379b04f-fbbd-4b7a-8ae7-e20452f15fc9

**Comment by Robel-003** [comment]
Fixed the typo in fetch call. Now the arrow functionality should be working

**Comment by cshimm** [comment]
The arrow functionality works on my end and the appropriate arrows disappear when reaching the first or last event.
I notice the event detail box shifts position when navigating from the first event to the second because when the 'previous' arrow gets rendered, it pushes everything over. In a future issue, it would be nice to have that event detail box fixed.

But otherwise it looks great!

**Review by cshimm — APPROVED** [review]

**Review by TuongPhamM — APPROVED** [review]
LGTM.

**Comment by miqo1385** [comment]
it look great in my end, I think it is exactly how it was intended.

**Review by heosman — APPROVED** [review]
It's working as expected!

**Pull request merged**
