### PR TITLE
nsc-events-nextjs_4_230_add-delete-event-functionality

### LINKED ISSUE #230: Event Details Page: Add functionality to delete button

### PR DESCRIPTION
**Pull request by Ali-7s**
Resolves #230 

1. Added delete event mutation function
2. Added isHidden optional field to activityDatabase interface
3. Added filter to filter out hidden events in useQuery fetch. 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/22021615/0c5f8485-98f8-42e7-beb9-e57142bb2cdb

### CODE REVIEW

**Review by Exochos — DISMISSED** [review]
image

Delete functionality appears to be working fine.
Couple of things, There is no visual documentation for the user that the deletion happened successfully, if we could use a toast or something like that to let the user know if it happened correctly or if an error occurred. Additionally, I am of the opinion that if the delete is successful we should navigate away from the deleted event after informing the user of a successful deletion.

**Comment by Exochos** [comment]
O also, perhaps a confirm button to make sure you really wanna delete?

**Comment by Ali-7s** [comment]
@Exochos @heosman I added the requested changes but it looks like we're using a different EventGetter component for the homepage now so the deletion doesn't reflect on the homepage

**Review by heosman — CHANGES_REQUESTED** [review]
I can see that you added a confirmation dialog box and a message that pops up if the deletion is successful. I am also redirected back to the home page. However, `isHidden` is not being updated to `true` in the database when the event is deleted in the frontend, like it is supposed to. And like you said, the events are not being hidden on the home page when they are successfully deleted. 

Please make sure these issues are both addressed in this PR. There will be differences, but Belinda's Closet recently integrated the delete functionality in their app so if you're stuck, you can check out their repo.

**Comment by Ali-7s** [comment]
> I can see that you added a confirmation dialog box and a message that pops up if the deletion is successful. I am also redirected back to the home page. However, `isHidden` is not being updated to `true` in the database when the event is deleted in the frontend, like it is supposed to. And like you said, the events are not being hidden on the home page when they are successfully deleted.
> 
> Please make sure these issues are both addressed in this PR. There will be differences, but Belinda's Closet recently integrated the delete functionality in their app so if you're stuck, you can check out their repo.

The backend updates on my side and I just added the filter to the new event getter components should it should work fine. 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/22021615/059d998f-caf8-4af6-9146-7b4323120994

**Review by heosman — APPROVED** [review]

**Comment by heosman** [comment]
It's working now, `isHidden` is updated to `true` in the database and the event is hidden on the frontend after it is deleted sucessfully. Good work!

**Pull request merged**
