### PR TITLE
Refactor (commented out) profile page

### LINKED ISSUE #5: UA landing page UI
As a Web/Android UI Developer, I will want to develop a very simple user authentication page. I will get in touch with the lead engineer should I have any questions or need support.

It might look like: 
 
image

Story Points: 6-12

### PR DESCRIPTION
**Pull request by Robel-003**
Can't seem to find the right resolve, but this pr is for issue 5(UA/UI landing page), in sprint 1. Commenting out the profile page for build to run

resolves #5

### CODE REVIEW

**Review by taylorpapke — DISMISSED** [review]
Running fine on my end. @theGaryLarson mentioned that he should be able to resolve these conflicts fairly easily as they were due to the branching strategy being implemented during the same time as this PR.

**Review by theGaryLarson — COMMENTED** [review]
I merged this branch into some changes I'm making locally to the workflows so everything aligns with android workflows.

This still doesn't build correctly because no there is an api route that is a blank page. To resolve this I added a stubbed out Profile Component to the top of the page. This  will come in with @theGaryLarson next PR.

**Comment by theGaryLarson** [comment]
Ok so merge conflicts are resolved and I added the stubbed Profile Component so npm run build will run successfully.

**Review by theGaryLarson — APPROVED** [review]
Downloaded branch and ran npm run build. It builds successfully!
Merge it!
image
image
image

**Review by taylorpapke — APPROVED** [review]

**Comment by Seiyaroo** [comment]
Going to run the other test now to see if the CI/CD will work per Robels implementations.

**Pull request merged**
