### PR TITLE
nsc-events-nextjs-9-495-redirect-to-event-after-creation

### LINKED ISSUE #495: Create Event Page: Redirect to event after creation
- [ ]  After successfully creating an event, user should be redirected to the newly created event.

### PR DESCRIPTION
**Pull request by Ali-7s**
Resolves #495 
* PR implements functionality that redirects user to event details page of the event they just created.

https://github.com/SeattleColleges/nsc-events-nextjs/assets/22021615/79424c11-912f-4781-a5e7-f66ce4c9bedd

### CODE REVIEW

**Review by bcko — APPROVED** [review]
Great job. Let's get this merged as soon as you have 2 or more approvals

**Review by ken-ni — APPROVED** [review]
Looks good to me, redirected to my test event after creating an event.

**Review by heosman — APPROVED** [review]
Works great, I was redirected to the event after I created it.

**Review by intisarosman1 — APPROVED** [review]
I am redirected to the event's page after I create it, LGTM

https://github.com/SeattleColleges/nsc-events-nextjs/assets/77607212/5889d4ba-c486-4427-b867-5605984de0dd

**Pull request merged**
