### PR TITLE
Ci refactor standardize with naming in android

### PR DESCRIPTION
**Pull request by theGaryLarson**
Just a refactor. Did not assign issue due to it being closed.
I uncommented npm run build step in workflow. As a result CI check fails.
The npm run build is failing due to errors in profile page.
Robels PR #40 will resolve this issue.

image

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
LGTM

**Comment by Seiyaroo** [comment]
@theGaryLarson Robels pull has been merged, I think since you, Taylor and Brandon have this you can run this now once the Merge Conflicts are resolved.

**Review by bcko — DISMISSED** [review]
LGTM

**Review by bcko — APPROVED** [review]

**Review by Seiyaroo — APPROVED** [review]
With BC giving thumbs up I am comfortable moving this forward.

**Pull request merged**
