### PR TITLE
nsc-events-nextjs_2_184_update-page.tsx

### LINKED ISSUE #184: Clean up accessibility issues such as removing alt text from logo

### PR DESCRIPTION
**Pull request by Exochos**
I updated the password visibility icons on the signup page to include aria-labels for screen readers.
This is considered best practices for accessibility and to help people with screen readers navigate better.

Resolves #184

### CODE REVIEW

**Review by heosman — COMMENTED** [review]
Just a heads-up, there are typos in both of the aria-labels for toggle password.

**Comment by Exochos** [comment]
> Just a heads-up, there's are typos in both of the aria-labels for toggle password.

Fixed

**Review by heosman — APPROVED** [review]
LGTM!

**Review by taylorpapke — APPROVED** [review]
Looks good and is working on my end. It is great that we are starting to take accessibility into consideration for our apps.

**Pull request merged**
