### PR TITLE
nsc-events-nextjs-4-234-display-upcoming-events-section

### LINKED ISSUE #234: Home Page Events Section: Display Upcoming Events Section
Relates to #231 

- This issue should add an upcoming events section on the home page with clickable events on the left. 
- The next upcoming event is also featured on the right side with a picture and link to its details.
- Events section will be displayed by itself when user is logged in. Otherwise, it will display under the welcome section which includes sign-in/up options.

Example:

Image

### PR DESCRIPTION
**Pull request by taylorpapke**
Resolves #234 

This PR creates a new events section on the home page comprised of 2 new components. The left side of the section has clickable upcoming events that act as buttons and will route to their event details. The section on the right is the next upcoming event from the left side featured with a picture and has a details button that can be clicked.

An observation I made is that the page is still using a mix of CSS along with MUI which I did not address at this time. Also, it appears that there is only a limit of 5 events that will load (perhaps for pagination?) which I will look into more. 

Signed in:
Screenshot 2024-03-07 at 2 02 46 AM

Signed out:
Screenshot 2024-03-07 at 1 58 38 AM

### CODE REVIEW

**Review by heosman — APPROVED** [review]
The upcoming events section of the page looks great. Clicking on the events in the left column, or the details button on the large event card on the right, routes me to the corresponding event detail page. 

By the way, the changes in this PR seem to have changed the appearance of the event detail page, so that should probably be addressed.

image

**Comment by brinkbrink** [comment]
Looks like you fixed what @heosman mentioned above:

Screen Shot 2024-03-08 at 11 06 55 AM

But the other pages are looking a little off from the screenshots you've posted:

Signed out:
Screen Shot 2024-03-08 at 11 07 07 AM

Signed in:
Screen Shot 2024-03-08 at 11 06 38 AM

For context, these sample events are being pulled from the northseattleappdev MongoDB.

**Comment by heosman** [comment]
@SeattleColleges/leadership Could we get another review on this pull request so it can be merged?

**Review by intisarosman1 — APPROVED** [review]
Works and functions as expected! Looking good

**Pull request merged**
