### PR TITLE
NSC_NextJS_Sprint_7_357_Change_Edit_to_Done

### PR DESCRIPTION
**Pull request by MuhammadNSC**
Change the "Edit" button to "Done" when finish selecting role
Screenshot 2024-05-23 at 6 44 26 PM
After the roles have been changed "Edit" button changes to "Don" and the page will refresh after clicking the "Done" button.

https://github.com/SeattleColleges/nsc-events-nextjs/assets/117953848/3c87d84a-3aab-4dc1-858d-30ae9d8e4657

### CODE REVIEW

**Comment by kaimanasse15** [comment]
Hi @MuhammadNSC , 
I have not seen any changed from edit to done yet. Am I missing something? Thank you
https://github.com/SeattleColleges/nsc-events-nextjs/assets/91504156/cffa726c-508d-4b21-81c3-d1450609767b

**Review by Robel-003 — APPROVED** [review]
This is working for me. I'm able to update the roles by editing a user's role and clicking done. 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/116779961/f010bd65-7542-4d46-94eb-f1778ca8547e

**Comment by Robel-003** [comment]
> Hi @MuhammadNSC ,
> I have not seen any changed from edit to done yet. Am I missing something? Thank you
> https://github.com/SeattleColleges/nsc-events-nextjs/assets/91504156/cffa726c-508d-4b21-81c3-d1450609767b

Yeah that's odd, it's working for me. There was another commit made so it might work now

**Comment by cshimm** [comment]
Working well on my end! I changed from admin to creator and saw the button text change to Done
image

I think it would also be nice to change the icon to a checkmark in a future PR!

**Review by cshimm — APPROVED** [review]

**Review by keiffer213 — CHANGES_REQUESTED** [review]
It doesn't seem to change the edit button to done unless you actually change the user role first

https://github.com/SeattleColleges/nsc-events-nextjs/assets/54779894/596049d2-877e-440d-aa28-8a049bbf3e9d

You can refer to this [PR ](https://github.com/SeattleColleges/belindas-closet-nextjs/pull/366)done from Belinda's as a guide

**Review by tinpham5614 — APPROVED** [review]

**Review by heosman — APPROVED** [review]
LGTM! @cshimm I agree with your suggestion, I think the edit icon should be changed ot a checkmark icon on the right side of the "Done" in a future issue. 

@keiffer213 I believe the edit button being changed to "Done" after opening the dialog is unnessessary at the moment. It might actually be better to replace the edit button with a cancel button when the edit user role dialog is opened (since there is no action until a role is chosen) and make the "Done" button appear once a role is chosen.

**Review by keiffer213 — APPROVED** [review]

**Pull request merged**
