### PR TITLE
nsc-events-nextjs-9-542-remove-errors-create-event-btn

### PR DESCRIPTION
**Pull request by Ali-7s**
Satisfies #542 
This PR removes the errors that appeared next to the create event button.

https://github.com/user-attachments/assets/66946970-1317-4f4a-a1f4-ec818cb9f0a0

### CODE REVIEW

**Review by keiffer213 — APPROVED** [review]
works for me! It doesn't show the redundant errors next to the button anymore

image

**Review by ken-ni — APPROVED** [review]
image
Looks good to me, I don't see the error messages that used to appear next to the create event button anymore!

**Review by intisarosman1 — APPROVED** [review]
The errors now only appear around their relevant fields instead of next to the submit button. It looks much better!
Screenshot 2024-07-16 200837

**Review by heosman — APPROVED** [review]
The error messages no longer appear next to the Create Event button.

image

**Pull request merged**
