### PR TITLE
nsc-events-nextjs_7_368_update_home_event_pagination_logic

### LINKED ISSUE #368: Home Page: Update the "get all events" query to support the new pagination method
The "get all events" query in the home page will need to be updated to support the new pagination strategy SeattleColleges/nsc-events-nestjs#119. Currently the number of events displayed is dependent on a numEvents parameter being passed as a parameter then increasing the numEvents value every time the "Load more events" button is clicked. The new pagination strategy employs the use of "pages" or chunks. These pages will return 5 events per page. The page value will be increased by 1 with each click of "Load more events" and the new page events will be added to the existing, already rendered events.

### PR DESCRIPTION
**Pull request by cshimm**
Resolves #368 

This PR updates the query and pagination logic to fit the refactor in the Nestjs repo. The behavior should be more or less identical, with some improvements that lend to a more predictable event order. 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/13278479/775e1de6-5336-4eb7-aa6e-eed275aea668

### CODE REVIEW

**Review by heosman — CHANGES_REQUESTED** [review]
I have a deleted event (Sample Event 4 in the screenshot) and an archived event (Sample Event 5) in my database. The archived event is hidden and doesn't seem to be included in the 5 active events on the home page, which is great. However, as you can see in the screenshot below, the deleted event, which has `isHidden` set to `true` in the database, is now displaying on the Home page.

image

image

**Review by heosman — APPROVED** [review]

**Review by taylorpapke — APPROVED** [review]
The event order along with the pagination on the home page look good:
Screenshot 2024-05-28 at 8 26 53 PM

**Review by keiffer213 — APPROVED** [review]
Along with everyone else this looks great and works well! 

image

**Comment by Diego-Cano** [comment]
Hey team,

I checked the latest pull request #373 on updating the home events pagination logic. The new page-based system works great and makes the pagination more predictable by loading 5 events per page. It's a solid update over the previous method of incrementing a numEvents parameter. The refactor to use TanStack Query has streamlined the logic and should enhance performance; I also appreciate the added detail of using URLSearchParams for managing query params, which enhances code readability and maintainability.

One issue was fixed previously with deleted events showing up on the home page despite having isHidden set to true in the database. This was resolved and now only active events are displayed. This change improved the accuracy of the event listings and avoids unwanted data from appearing on the user interface.

The use of TanStack Query for this implementation is awesome and enhances performance. It would be good to test thoroughly to catch any potential edge cases, especially with the event filtering logic at some point.  

I found a helpful link for pagination strategies: [guide on efficient pagination](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API). Great work, Cameron!

**Comment by nwm516** [comment]
I had some test events created with similar titles with a numeric after their names. I also highlight in the video two events that indicate a deletion and an archived event. Both of the latter events do not show, so these changes also LGTM. 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/36825393/6178ba8e-b8de-4a9e-b935-cccbe68cc98a

**Review by ogarmela — APPROVED** [review]

**Pull request merged**
