### PR TITLE
nsc-events-nextjs-7-381-my-events-page-pagination

### PR DESCRIPTION
**Pull request by cshimm**
### Note this PR depends on SeattleColleges/nsc-events-nestjs#120. Please check out branch `refactor-120-update-get-events-by-user-controller` in the backend repo when testing these changes.
This PR implements pagination on the My Events page. It also implements the functionality to refetch queries on any event mutation (add, update, delete, archive). Without this safeguard, duplicate events can be fetched, leading to unexpected behavior regarding the pagination.  5 events are loaded by default, and another 5 will be loaded and rendered every time the "Load more events" button is clicked until the current page returns less than 5 events signifying it is the last page so the button will be hidden. There is the case where the last page returns 5 events. This means clicking the Load More Events button will disappear but no new events will render. My thought would be to add API route that returns a count of events given a certain query, but there may be a better way that I'm not aware of currently. 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/13278479/244094e8-ff05-4000-a997-67cc5d14d0a0

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Everything seems to be working as expected:
Screenshot 2024-05-28 at 9 03 51 PM

**Review by Robel-003 — APPROVED** [review]
Working for me as well. This is a great feature for this page! 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/116779961/497631e8-c74d-4500-8aa8-0299787aa4fa

**Review by heosman — APPROVED** [review]
It's working great, good work.

image

**Comment by MuhammadNSC** [comment]
This function works as described in the PR. After clicking on my event button in the dashboard page, i'm directed to my-event page. 

https://github.com/SeattleColleges/nsc-events-nextjs/assets/117953848/b81eff47-f7ec-46fe-9e72-a367558ffd0f

**Pull request merged**
