### PR TITLE
nsc-events-nextjs_6_314_qa-testing-for-creator-page

### PR DESCRIPTION
**Pull request by kaimanasse15**
Resolve: https://github.com/SeattleColleges/nsc-events-nextjs/issues/314

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks good and I'm seeing the tests passing during CI:
Screenshot 2024-05-05 at 2 20 30 PM
Screenshot 2024-05-05 at 2 20 07 PM

**Review by heosman — APPROVED** [review]
The tests for the creator page passed.

image

**Comment by MuhammadNSC** [comment]
All the tests run were passed
Screenshot 2024-05-08 at 7 20 46 PM

**Review by nickolasram — APPROVED** [review]
I’m seeing all the tests are passing on my end 👍 but this branch seems to be behind main. It should be able to be merged into main once you update it

**Pull request merged**
