### PR TITLE
nsc-events-nextjs-5-258_app_crashes_when_refreshing_event_detail_page

### LINKED ISSUE #258: BUG: App crashes when refreshing Event Detail page
The app throws an Unhandled Runtime Error and crashes when refreshing the Event Detail page

**To Reproduce**\
1. Nagivate home.
2. Click an event to navigate to the event details page
3. Refresh the page.
image

**Expected behavior**\
The app should not crash and render the event details again properly on refresh.

**Desktop (please complete the following information):**\
 - OS: Windows 10
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by cshimm**
Resolves #258 

Description:
This fix will ensure that the data retrieved from the 'event' query is valid before performing find() on it.

Before fix:
https://github.com/SeattleColleges/nsc-events-nextjs/assets/13278479/fb1dd9a3-717d-4d1c-9b27-66d067aee7c0

After fix:
https://github.com/SeattleColleges/nsc-events-nextjs/assets/13278479/e4e46cb0-f528-4eb8-be40-69c4143b3d72

### CODE REVIEW

**Review by bennettsf — APPROVED** [review]
event-detail page properly refreshes without crashing.  

https://github.com/SeattleColleges/nsc-events-nextjs/assets/33855430/a3260b47-9c88-44cf-99af-834f2415c3ca

**Review by taylorpapke — APPROVED** [review]
Works on my end. Thanks for providing before and after videos!

**Review by IsaacJrTypes — APPROVED** [review]
Great work! It's working as intended

CleanShot 2024-04-22 at 14 12 31

**Review by intisarosman1 — APPROVED** [review]
Works as expected with no crashes. Looks good to merge!

**Pull request merged**
