### PR TITLE
nsc-events-nextjs_6_285_nav-bar-updates

### PR DESCRIPTION
**Pull request by miqo1385**
This is a pull request!

Please use the following format for the title:
npc-event-nextjs _ sprint 6 _ #285 _ Nav Bar

updates on the nav bar.

https://github.com/SeattleColleges/nsc-events-nextjs/assets/97195623/bc509f55-24d5-40fe-bbce-720cdb8a61d7

### CODE REVIEW

**Comment by miqo1385** [comment]
still work in progress.

**Comment by heosman** [comment]
@miqo1385 I'll convert this PR to a draft since you're still working on it.

**Review by Robel-003 — COMMENTED** [review]
I'm able to see the icon right next to NSC Events in the header. I also see the change from "Home" to "Events". It seems like I have to shrink the web window to see the NSC star logo appear

**Comment by cshimm** [comment]
@Robel-003 I believe that is because he is implementing responsive styles for the navbar, so I think that part is working as intended.

**Pull request closed without merging**
