### PR TITLE
nsc-events-nextjs-4-237-create-event-functionality

### LINKED ISSUE #236: USER STORY: Create Event Functionality
As a developer I want to integrate the frontend and backend allowing admins and creators to create events. In order to makes this integration successful, I first want to make sure all the fields in the backend and schema are caught up to the frontend. Upon creating an event, I want to display a message on the frontend showing that the event was successfully created or failed to create an event

Issue:
- [ ] Make sure all fields in the backend and schema are caught up to the  frontend
- [ ] #237
- [ ] Display a message on the frontend if creating event is successful or if it failed

### PR DESCRIPTION
**Pull request by Robel-003**
Resolves #236 #237  

_**In order for this [pr](https://github.com/SeattleColleges/nsc-events-nestjs/pull/92) to work, this pr in the nestjs backend needs to be checked/merged since it relies on the updated backend and schema fields**_

This pr integrates the frontend and backend to start the event creation process through a POST fetch call successfully creating an event. Upon entering all the fields in the create event page _correctly_ and clicking “Create Event”, it should create an event and store that event into the database. A prompt below the “Create Event” button will signify the successful creation of an event.

- Screenshot 2024-03-07 at 9 27 08 PM
- Screenshot 2024-03-07 at 9 27 25 PM
- Screenshot 2024-03-07 at 9 44 58 PM

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Everything is working for me:
Screenshot 2024-03-08 at 1 08 18 AM
Screenshot 2024-03-08 at 1 08 49 AM

**Review by brinkbrink — COMMENTED** [review]
I'm receiving this error when I try to create an event:

Screen Shot 2024-03-08 at 11 29 52 AM

The user I'm signed in as is an admin (I wouldn't be able to get to this page otherwise). I am also using the branch from the PR you reference in the description for Nest. Anybody know where I went wrong? How did you get it working @taylorpapke ?

I am using a different database, so maybe that's a clue? I'm using the northseattleappdev MongoDB.

**Comment by Robel-003** [comment]
@brinkbrink that seems like a permission issue but if you're signed in as a admin that shouldn't happen. Within that same mongo db try manually inputing a new user with admin access into mongo and logging in with that new user.

**Review by heosman — CHANGES_REQUESTED** [review]
I was able to create an event successfully.

image
image

Similar to what I mentioned in my review for the PR on the backend, the Event Cost and Event Website fields should be removed.

**Review by heosman — APPROVED** [review]

**Comment by heosman** [comment]
@Robel-003 What happened with the image picker? I noticed that it's a text field now.

**Pull request merged**
