### PR TITLE
Home Page: Conditionally render Intro Screen

### LINKED ISSUE #202: Home Page: hide the intro and only display events if logged in:
As a developer I would like to be able to:
"When signed in, hide the “Welcome to North Seattle College Events” text, “Sign Up”, “Sign In” card so that only the events are displayed"

### PR DESCRIPTION
**Pull request by Exochos**
I added a circular progress indicator while I load the useEffect hook to check if there is a token present in localstorage, if there is I will only display the events and not the intro screen. 
I also added the token in via the signIn page so its stored both via the signUp and SignIn page.

Before Login:
BeforeLogin

After Login:
AfterLogin

As a side note I noticed that the intro screen and some of the events are overflowing the navBar at small screen sizes and this should be fixed in another issue.

To test this login as usual with the backend running and then navigate to the home page. You can then use 'localStorage.clear();' in the console to clear the token and refresh the page so see the difference.

Resolves #202

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
When signed in, the following intro screen is displayed:
Screenshot 2024-02-20 at 12 51 58 AM
Upon signing out by using 'localStorage.clear();' in the javascript console, the intro screen is then displayed as the following:
Screenshot 2024-02-20 at 12 55 43 AM

**Review by heosman — CHANGES_REQUESTED** [review]
When I sign in, the Intro Screen is hidden on the Home page so I can see only events, which is great. However if I sign up (after clearing localStorage), the Intro Screen is hidden in this case also, so I am unable to navigate to the Sign In page to login using the UI. Signing up should not trigger the Intro Screen being hidden.

**Comment by Exochos** [comment]
> When I sign in, the Intro Screen is hidden on the Home page so I can see only events, which is great. However if I sign up (after clearing localStorage), the Intro Screen is hidden in this case also, so I am unable to navigate to the Sign In page to login using the UI. Signing up should not trigger the Intro Screen being hidden.

So the reason this is happening is that the sign up page is storing the token returned from the successful sign up. Which is the same token which is returned from a successful signin. So upon a successful sign up the system sees the user as signed in. Fixes for this would be to not store the token upon signup, or to instead of redirecting to signin after a successful signup instead redirecting to the event page instead.

**Comment by heosman** [comment]
> > When I sign in, the Intro Screen is hidden on the Home page so I can see only events, which is great. However if I sign up (after clearing localStorage), the Intro Screen is hidden in this case also, so I am unable to navigate to the Sign In page to login using the UI. Signing up should not trigger the Intro Screen being hidden.
> 
> So the reason this is happening is that the sign up page is storing the token returned from the successful sign up. Which is the same token which is returned from a successful signin. So upon a successful sign up the system sees the user as signed in. Fixes for this would be to not store the token upon signup, or to instead of redirecting to signin after a successful signup instead redirecting to the event page instead.

We will be redirecting the user to the Sign In page after successfully signing up, but the best case scenario is that as long as the user is not signed in, the Intro Screen should be visible. If the same token is stored after signing in, then is storing the token upon sign up necessary? Maybe we should only store the token after signing in. Would this be an issue @tinpham5614?

**Comment by Exochos** [comment]
> > > When I sign in, the Intro Screen is hidden on the Home page so I can see only events, which is great. However if I sign up (after clearing localStorage), the Intro Screen is hidden in this case also, so I am unable to navigate to the Sign In page to login using the UI. Signing up should not trigger the Intro Screen being hidden.
> > 
> > 
> > So the reason this is happening is that the sign up page is storing the token returned from the successful sign up. Which is the same token which is returned from a successful signin. So upon a successful sign up the system sees the user as signed in. Fixes for this would be to not store the token upon signup, or to instead of redirecting to signin after a successful signup instead redirecting to the event page instead.
> 
> We will be redirecting the user to the Sign In page after successfully signing up, but the best case scenario is that as long as the user is not signed in, the Intro Screen should be visible. If the same token is stored after signing in, then is storing the token upon sign up necessary? Maybe we should only store the token after signing in. Would this be an issue @tinpham5614?

From Tin: "Tin Pham
  [6:22 PM] In my opinion, if the implementation is once signed up successfully and automatically signed in afterward, then we don't need to redirect to the sign-in page. Otherwise, we redirect the user to the sign-in page to log in (convenience for users)."

**Comment by heosman** [comment]
> > > > When I sign in, the Intro Screen is hidden on the Home page so I can see only events, which is great. However if I sign up (after clearing localStorage), the Intro Screen is hidden in this case also, so I am unable to navigate to the Sign In page to login using the UI. Signing up should not trigger the Intro Screen being hidden.
> > > 
> > > 
> > > So the reason this is happening is that the sign up page is storing the token returned from the successful sign up. Which is the same token which is returned from a successful signin. So upon a successful sign up the system sees the user as signed in. Fixes for this would be to not store the token upon signup, or to instead of redirecting to signin after a successful signup instead redirecting to the event page instead.
> > 
> > 
> > We will be redirecting the user to the Sign In page after successfully signing up, but the best case scenario is that as long as the user is not signed in, the Intro Screen should be visible. If the same token is stored after signing in, then is storing the token upon sign up necessary? Maybe we should only store the token after signing in. Would this be an issue @tinpham5614?
> 
> From Tin: "Tin Pham [6:22 PM] In my opinion, if the implementation is once signed up successfully and automatically signed in afterward, then we don't need to redirect to the sign-in page. Otherwise, we redirect the user to the sign-in page to log in (convenience for users)."

I see. I think we should roll back the changes that were just merged in the recent PR then.

**Review by heosman — APPROVED** [review]

**Pull request merged**
